INSERT INTO Žanrs VALUES
    ('Asa sižeta', 'Strauji ritējošas spēles, kas prasa ātrus refleksus un stratēģisko domāšanu.'),
    ('Piedzīvojumu', 'Spēles, kas koncentrējas uz izpēti, stāstu un mīklu risināšanu.'),
    ('Casual', 'Viegli spēlējamas spēles, kas piemērotas plašam auditorijam.'),
    ('Indie', 'Spēles, ko izstrādā mazas neatkarīgas izstrādātājfirmas vai studijas.'),
    ('MMORPG', 'Tiešsaistes spēles, kas iesaista lielu skaitu spēlētāju.'),
    ('Simulācija', 'Spēles, kas imitē reālas situācijas vai sistēmas.'),
    ('Stratēģija', 'Spēles, kas prasa plānošanu, resursu pārvaldību un taktisko domāšanu.'),
    ('Sports', 'Sporta spēles, kas ietver dažādas sporta veidus un sacensības.'),
    ('RPG', 'Lomu spēles, kurās spēlētāji attīsta savu tēlu un piedzīvo dažādas piedzīvojumus.'),
    ('Puzles', 'Mīklu un loģikas spēles, kas prasa domāšanu un problēmu risināšanu.'),
    ('Platformas spēle', 'Spēles, kurās galvenais mērķis ir pārvietoties pa platformām.'),
    ('Sacīkšu', 'Spēles, kurās spēlētāji sacenšas ar automašīnām vai citiem transportlīdzekļiem.'),
    ('Šautene', 'Spēles, kurās spēlētāji izmanto ieročus, lai cīnītos ar pretiniekiem.'),
    ('Šausmu', 'Spēles, kas balstītas uz šausmu stāstiem un atmosfēru.'),
    ('Cīņas', 'Cīņas spēles, kurās spēlētāji kontrolē tēlus, kas cīnās ar citiem tēliem.'),
    ('Mūzika', 'Mūzikas spēles, kas ļauj spēlētājiem piedalīties mūzikas radīšanā vai izpildīšanā.'),
    ('Vizuālā novele', 'Spēles, kas koncentrējas uz teksta lasīšanu un lēmumu pieņemšanu.'),
    ('VR', 'Virtuālās realitātes spēles, kas paredzētas VR ierīcēm.'),
    ('Kāršu spēle', 'Kāršu spēles, kas ietver kāršu kolekcionēšanu un taktisko cīņu.'),
    ('Arcade', 'Spēles, kas balstītas uz vecās skolas spēļu automātu spēlēm.'),
    ('Izglītojošs', 'Izglītojošas spēles, kas māca spēlētājiem dažādas prasmes un zināšanas.'),
    ('Idle', 'Spēles, kas ļauj spēlētājiem gūt panākumus ar minimālu ieguldījumu.'),
    ('Galda spēle', 'Spēles, kas balstītas uz galda spēlēm.'),
    ('Sandbox', 'Brīvas izpētes spēles, kas ļauj spēlētājiem veidot un eksperimentēt.'),
    ('Roguelike', 'Spēles ar procedūrāli ģenerētām līmeņiem un palielinātu grūtību.'),
    ('Pilsētu būvētājs', 'Spēles, kurās spēlētāji plāno un attīsta pilsetas vai civilizācijas.'),
    ('Gājieniem balstīta', 'Griežu pamata stratēģijas spēles.'),
    ('MOBA', 'Daudzspēlētāju tiešsaistes kaujas laukuma spēles.'),
    ('FPS', 'Pirmās personas šaušanas spēles.'),
    ('RTS', 'Reāllaika stratēģijas spēles.'),
    ('Co-op', 'Spēles, kurās spēlētāji sadarbojas, lai sasniegtu kopīgus mērķus.'),
    ('Izdzīvošana', 'Spēles, kurās spēlētājiem jāizdzīvo pretinieku uzbrukumos un vides apstākļos.'),
    ('Maskēšanās', 'Spēles, kurās spēlētājiem jāizvairās no konfrontācijām, izmantojot slepenību.'),
    ('Randiņu simulācijas', 'Simulatora spēles, kurās spēlētāji veido attiecības ar citiem tēliem.'),
    ('Tēmē un spied', 'Spēles, kas ietver peles klikšķināšanu, lai risinātu mīklas un iesaistītos stāstā.');