INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (1, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (15, 'RPG');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (4, 'Piedzīvojumu');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (19, 'Indie');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (6, 'Simulācija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (1, 'Stratēģija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (15, 'Fantāzija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (1, 'Multiplayer');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (22, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (4, 'Viena spēlētāja');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (3, 'Zinātniskā fantastika');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (5, 'Šausmu');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (1, 'Šautene');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (3, 'Platformas spēle');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (5, 'Puzzle');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (4, 'Bagāts stāsts');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (1, 'Izdzīvošana');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (26, 'Maskēšanās');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (6, 'Sandbox');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (32, 'Izpētīšana');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (4, 'Atmosfēriska');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (18, 'Casual');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (1, 'Taktiskā');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (2, 'Retro');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (58, 'Anime');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (48, 'Viduslaiku');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (7, 'Postapokaliptisks');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (18, 'Vēsturisks');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (3, 'Kosmosā');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (10, 'Komēdija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (87, 'Psiholoģiskā');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (20, 'Gājieniem balstīta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (6, 'Karš');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (20, 'Vadība');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (71, 'Detektīvs');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (3, 'Sports');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (43, 'Sacīkšu');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (78, 'Cīņa');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (3, 'Kiberpanks');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (23, 'Reālā laika');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (12, 'Amatniecība');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (40, 'Mūzika');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (34, 'Skaists');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (14, 'Vietējā sadarbība');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (36, 'Loot');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (43, 'Kailums');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (19, '2D');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (46, 'Izvēlei ir nozīme');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (113, 'Drāma');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (17, 'Reālistisks');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (61, 'Sirreāls');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (70, 'Hack and Slash');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (21, 'Būvēšana');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (5, 'Zombiji');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (18, 'Otrais pasaules karš');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (1, 'Sacensību');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (1, 'Vecā skola');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (57, 'JRPG');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (77, 'Supervaroņi');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (80, 'VR');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (32, 'MMORPG');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (19, 'Indie');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (15, 'MOBA');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (1, 'FPS');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (15, 'RTS');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (2, 'Co-op');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (32, 'PvE');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (3, '3D');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (19, '2D');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (8, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (9, 'FPS');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (11, 'FPS');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (13, 'Zombiji');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (16, 'Platformas spēle');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (24, 'FPS');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (25, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (27, 'Maskēšanās');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (28, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (29, 'Kiberpanks');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (30, 'FPS');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (31, 'FPS');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (33, 'FPS');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (35, 'Stratēģija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (37, 'Zombiji');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (38, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (39, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (41, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (42, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (44, 'Izpētīšana');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (45, 'Sacīkšu');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (47, 'Šausmu');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (49, 'RPG');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (50, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (51, 'RPG');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (52, 'RPG');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (53, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (54, 'Casual');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (55, 'RPG');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (56, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (59, 'Sacīkšu');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (60, 'Simulācija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (62, 'Loot');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (63, 'Šausmu');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (64, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (65, 'Stratēģija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (66, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (67, 'Puzzle');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (68, 'Stratēģija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (69, 'Sandbox');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (72, 'Indie');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (73, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (74, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (75, '2D');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (76, 'Maskēšanās');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (79, 'Kosmosā');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (81, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (82, 'Kosmosā');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (83, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (84, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (85, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (86, 'Izdzīvošana');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (88, 'RPG');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (89, 'Sandbox');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (90, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (91, 'Simulācija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (92, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (93, 'Indie');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (94, 'Piedzīvojumu');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (95, 'Izdzīvošana');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (96, 'Indie');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (97, 'Izdzīvošana');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (98, 'Multiplayer');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (99, 'Asa sižeta');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (100, 'Simulācija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (101, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (102, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (103, 'Zombiji');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (104, 'Viduslaiku');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (105, 'Cīņa');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (106, 'Cīņa');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (107, 'Šausmu');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (108, 'FPS');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (109, 'VR');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (110, 'Bagāts stāsts');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (111, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (112, 'VR');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (114, 'Simulācija');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (115, 'RPG');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (116, 'VR');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (117, 'Cīņa');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (118, 'Atvērtā pasaule');
INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES (119, 'RPG');
