INSERT INTO MantasKlase (Nosaukums, Apraksts, SpēleID) VALUES
	('Dvēseļu Lāčplēša Krekls', NULL, 36),
	('Dzelzs', 'Dzelzs ir būtiska materiāla sastāvdaļa daudzu ieroču un bruņu ražošanā.', 36),
	('Akadēmijas Mistērijas Jaka', NULL, 36),
	('Zelta Lāčplēša Izdzīvošanas Iešana', NULL, 36),
	('Melnās Pilsētas Ķirsis', 'Dolor neque cum recusandae cupiditate facere.', 36),
	('Vētras Akadēmijas Valstības Jaka', NULL, 36),
	('Ķivere', 'Ķivere ir būtiska aizsardzība kaujā, kas aizsargā pret smagiem triecieniem.', 36),
	('Lielās Kalna Krekls', 'Deserunt praesentium totam placeat illum corrupti nemo sit maiores.', 36),
	('Izpētītāju Bikses', 'Explicabo dolor non sapiente molestiae nam minus ut eum voluptas laboriosam maxime quas corrupti.', 53),
	('Krekls', 'Šis krekls ir izgatavots no ērtiem un izturīgiem materiāliem, lai jūs varētu ceļot ar stilu.', 4),
	('Senču Bulta', NULL, 4),
	('Lielās Zobens', NULL, 4),
	('M4A4', 'M4A4 piedāvā stabilu uguni un precīzu mērķēšanu, lai apkarotu jebkuru draudu.', 4),
	('Pēdējās Pilsētas Jaka', NULL, 4),
	('Jūras Pirātu Plēve', NULL, 4),
	('Vētras Kalna Izdzīvošanas Bikses', NULL, 4),
	('Jūras Mistērijas Iešana', 'Occaecati a doloremque nihil provident quos mollitia.', 4),
	('Draudzīgā M4A4', NULL, 4),
	('Leģendārā Bumba', NULL, 2),
	('Burvju Lāčplēša Ķēde', 'Totam aliquid voluptate aliquam a dolorum amet natus.', 2),
	('Pilsētas Pirātu Plēve', 'Laboriosam ad consectetur natus labore magnam incidunt autem ab nihil.', 2),
	('Jūras Dzelzs', NULL, 2),
	('Pasaules Ķivere', 'Dolore blanditiis laborum in eius corrupti.', 2),
	('Vētras Pasaules Bumba', NULL, 2),
	('Izpētītāju M4A4', 'Placeat provident beatae alias corporis fugiat placeat harum.', 2),
	('Kosmosa Akadēmijas Pilis', 'Magnam similique quidem officia voluptates illum reprehenderit praesentium nulla blanditiis placeat repellendus similique.', 2),
	('Lāčplēša Mistērijas Cepure', 'Expedita laborum similique commodi magni debitis alias quae vero id temporibus iure eligendi placeat.', 2),
	('Kosmosa Paradīzes M4A4', NULL, 3),
	('Bikses', 'Izgatavots no augstas kvalitātes sastāvdaļām, šis Bikses nodrošina lielisku atveseļošanos.', 3),
	('Draudzīgā Ķirsis', 'Voluptatem pariatur expedita velit molestiae iste exercitationem.', 3),
	('Bastions Izpētītāju Kaujas Āmurs', NULL, 3),
	('Lielās Bikses', 'Amet eum at magnam officia explicabo sequi in consequatur et.', 1),
	('Senču Paradīzes Iešana', 'Dolorem a quis fuga voluptatibus quae omnis ad facere deserunt.', 1),
	('Zirgs', NULL, 1),
	('Cerības Bikses', 'Ducimus perferendis eligendi asperiores rerum blanditiis ratione suscipit eos eum soluta odit dolorem.', 1),
	('Lāčplēša Meža Dzelzs', 'Sit eveniet vitae omnis ipsum dolores provident laudantium.', 1),
	('Melnās Lāčplēša Cepure', 'Voluptate adipisci vitae alias voluptatibus recusandae alias maxime occaecati ut.', 1),
	('Kalna Ķirsis', NULL, 1),
	('Maģija', 'Voluptatibus assumenda sint iste eaque quisquam ipsam quaerat cum sint eligendi fugiat.', 1),
	('Leģendārā Maģija', NULL, 6),
	('Valstības Zobens', 'Corporis voluptatum enim enim quam excepturi.', 6),
	('Dvēseļu Vēju Cepure', 'Quia tempora molestiae veritatis dolorem inventore non dolor alias necessitatibus sint consequatur eum.', 6),
	('Zelta Cerības Bulta', NULL, 6),
	('Draudzīgā Vēju Izdzīvošanas Bumba', 'Repellendus debitis animi accusantium sit tempore eaque illo voluptatibus facere.', 6),
	('Karalienes Izdzīvošanas ŅSG', 'Voluptatum perferendis beatae porro nesciunt quos ipsum modi quisquam laudantium error nemo nostrum accusamus.', 6),
	('Senču Meža Bulta', NULL, 5),
	('Dvēseļu Pilsētas Iešana', 'Molestias expedita ullam facere suscipit quae ipsa est.', 5),
	('Cepure', 'Šī cepure ir izgatavota no visizturīgākajiem materiāliem, lai aizsargātu jūs pret sauli un lietu.', 5),
	('Vētras Reģiona Izpētītāju Jaka', 'Aspernatur vitae quae officia nihil nemo ullam praesentium.', 5),
	('Kosmosa Pilsētas Plēve', 'Recusandae voluptatem enim vel quod porro occaecati quia quaerat exercitationem dolore aperiam cupiditate.', 5),
	('Melnās Cīņas Pilis', NULL, 5),
	('Ziemeļu Lāčplēša M4A4', 'Quo maxime nam autem ipsum provident maxime quod adipisci.', 5),
	('Ziemeļu Bastions Meža Zobens', NULL, 5),
	('Ziemeļu Kalna Valstības Kaujas Āmurs', NULL, 7),
	('Krekls', 'Šis krekls ir izgatavots no ērtiem un izturīgiem materiāliem, lai jūs varētu ceļot ar stilu.', 7),
	('Kosmosa Pilis', NULL, 7),
	('Lielās Pilsētas Maģija', NULL, 7),
	('Draudzīgā ŅSG', NULL, 7),
	('Izdzīvošanas Kaujas Āmurs', 'Minus nam quis delectus possimus placeat quam tempora omnis possimus.', 7),
	('Izpētītāju Šaržieris', 'Voluptatum voluptatibus iure labore nam tempore adipisci blanditiis ipsa.', 7),
	('Mistērijas Dzelzs', 'Aut quod odit rem dignissimos alias praesentium libero ab officia inventore earum laboriosam.', 7),
	('Lāčplēša Krekls', 'Veritatis aliquam asperiores consectetur placeat laudantium quas vitae vero omnis eum.', 7),
	('Leģendārā Ķirsis', NULL, 8),
	('Akadēmijas Izdzīvošanas Ķivere', 'Itaque nesciunt ab aperiam laborum consectetur vero dignissimos nam sed ducimus.', 8),
	('Plēve', NULL, 8),
	('Pilsētas Cīņas ŅSG', 'Eligendi nam veritatis illum et quisquam nobis porro.', 18),
	('Kalna Izpētītāju Jaka', NULL, 18),
	('Zelta Krekls', 'Mollitia sed delectus pariatur distinctio officia voluptates quas.', 18),
	('Vētras Iešana', 'Reiciendis cupiditate tenetur delectus debitis modi perspiciatis voluptate vero exercitationem possimus.', 18),
	('Tūre Šaržieris', NULL, 18),
	('Lielās Bastions Ķivere', 'Adipisci esse amet laboriosam id vel fugit sequi corrupti aliquid doloremque id.', 18),
	('Meža Maģija', NULL, 18),
	('Meža Ķivere', NULL, 18),
	('Leģendārā Paradīzes Bikses', 'Asperiores aliquid eligendi nemo consequatur eaque suscipit architecto praesentium sint explicabo sunt aliquid.', 20),
	('Kosmosa Iešana', NULL, 20),
	('Kosmosa Vēju Paradīzes Dzelzs', NULL, 20),
	('M4A4', 'M4A4 piedāvā stabilu uguni un precīzu mērķēšanu, lai apkarotu jebkuru draudu.', 20),
	('Melnās Karalienes Cepure', NULL, 20),
	('Reģiona Bikses', 'Et mollitia reiciendis fuga autem tempore quod sint facilis distinctio perferendis rem.', 20),
	('Zelta Ķēde', 'Minus quae dignissimos error recusandae delectus veritatis sunt animi totam nemo.', 20),
	('Draudzīgā Cerības Cīņas Ķēde', NULL, 20),
	('Cerības Cīņas Jaka', 'Modi quasi molestiae dolorum eos explicabo magnam voluptatem sit molestias at dolorem eaque.', 20),
	('Pēdējās Pasaules Šaržieris', 'Architecto facere sequi non nemo soluta aliquam velit minus ipsum.', 21),
	('Dvēseļu Pasaules Bumba', NULL, 21),
	('Vēju Plēve', NULL, 21),
	('Burvju Akadēmijas Ķivere', 'Deserunt modi optio nulla earum dolore eum ea occaecati nostrum.', 21),
	('Bulta', NULL, 21),
	('Jūras Pilis', NULL, 21),
	('Pirātu Iešana', 'Sapiente incidunt vitae neque deleniti sapiente impedit similique quae laboriosam incidunt.', 21),
	('Ziemeļu Kalna Kaujas Āmurs', NULL, 21),
	('Pirātu Bikses', NULL, 21),
	('Lāčplēša Paradīzes Bumba', NULL, 26),
	('Melnās Bastions Izpētītāju Jaka', NULL, 28),
	('Vētras Bastions Jaka', NULL, 28),
	('Leģendārā Jūras Pilis', NULL, 28),
	('Valstības Zirgs', NULL, 28),
	('Senču Izdzīvošanas Pilis', 'Corrupti amet itaque vel occaecati quo dicta.', 28),
	('Pilsētas Pirātu Pilis', 'Inventore incidunt id voluptatem soluta sed laborum.', 28),
	('Ziemeļu Pirātu Iešana', 'Quas similique ut iure eligendi nisi.', 23),
	('Pirātu Kaujas Āmurs', NULL, 23),
	('Reģiona Tūre Bikses', NULL, 23),
	('Melnās Bastions Cepure', 'Ducimus alias eveniet molestiae repudiandae eum.', 23),
	('Akadēmijas Bikses', 'Placeat autem cupiditate porro dignissimos fuga occaecati.', 10),
	('Kosmosa Cīņas M4A4', 'Animi impedit sed corrupti eius ut quo suscipit cupiditate illo.', 11),
	('Cīņas Zobens', NULL, 11),
	('Kosmosa Pirātu M4A4', NULL, 11),
	('Melnās Krekls', 'Libero asperiores incidunt odit amet eius inventore inventore deserunt cupiditate vel incidunt.', 11),
	('Melnās Cerības Valstības Bikses', NULL, 11),
	('Cerības Izdzīvošanas Ķēde', NULL, 11),
	('Pasaules Ķirsis', NULL, 12),
	('Leģendārā Pasaules Šaržieris', NULL, 12),
	('Ziemeļu Ķivere', 'Architecto a veniam deserunt repudiandae aspernatur quia.', 12),
	('Zelta Lāčplēša Cīņas Bumba', 'Est itaque consectetur ad nam veritatis sint voluptatibus tenetur modi.', 12),
	('Cerības Mistērijas ŅSG', 'Aut voluptas inventore molestias asperiores ducimus corrupti fugiat eveniet sit molestiae.', 12),
	('Lielās Izdzīvošanas Dzelzs', NULL, 12),
	('Pēdējās Lāčplēša Bumba', NULL, 12),
	('Burvju Karalienes Pasaules Bumba', 'Distinctio doloremque exercitationem at sapiente repellendus ullam velit excepturi aut dolorem.', 12),
	('Melnās Dzelzs', 'Nam sapiente voluptas veritatis sapiente harum.', 12),
	('Akadēmijas Cīņas Dzelzs', 'Unde commodi eveniet officiis recusandae quas quaerat praesentium labore ipsa velit expedita sint.', 31),
	('Zelta Izdzīvošanas Maģija', NULL, 31),
	('Vētras Ķēde', 'Possimus animi reprehenderit molestias quidem eveniet maxime aliquam reiciendis veritatis nam atque.', 31),
	('Jūras Šaržieris', 'Tempora omnis recusandae laborum harum atque cum neque amet architecto quasi.', 31),
	('Lielās Akadēmijas Paradīzes Plēve', NULL, 31),
	('Leģendārā Lāčplēša Maģija', NULL, 31),
	('Leģendārā Lāčplēša Paradīzes Kaujas Āmurs', NULL, 31),
	('Bastions Bumba', NULL, 31),
	('Ziemeļu Karalienes Maģija', 'Saepe occaecati nemo consequuntur minima cum sed facilis.', 31),
	('Kalna Meža Ķēde', 'Sapiente asperiores porro voluptatum tempora officiis perferendis fugit unde dolorum quas numquam.', 39),
	('Bastions ŅSG', NULL, 39),
	('Zelta Paradīzes Plēve', 'Repellat nostrum voluptates libero nesciunt eaque repudiandae nesciunt beatae animi enim praesentium libero.', 39),
	('Pirātu M4A4', NULL, 39),
	('Akadēmijas Maģija', 'Ab fugiat quibusdam fuga neque eum officia repudiandae.', 39),
	('Kosmosa Kalna M4A4', NULL, 39),
	('Kalna Cīņas Cepure', NULL, 40),
	('Burvju Senču Paradīzes Kaujas Āmurs', NULL, 40),
	('Jūras ŅSG', NULL, 40),
	('Cerības Dzelzs', NULL, 40),
	('Bastions Cīņas Iešana', 'Voluptatibus reiciendis delectus dolor dignissimos dicta eaque consequuntur consectetur eius.', 40),
	('Maģija', 'Numquam sint accusamus vel necessitatibus repellendus et non perferendis ab aut.', 40),
	('Bastions Cepure', 'Sed deleniti explicabo aliquam culpa cupiditate id hic pariatur autem adipisci iusto.', 40),
	('Krekls', 'Šis krekls ir izgatavots no ērtiem un izturīgiem materiāliem, lai jūs varētu ceļot ar stilu.', 41),
	('Zelta Vēju Dzelzs', NULL, 41),
	('Kosmosa Bastions Cīņas Pilis', NULL, 41),
	('Ziemeļu Cerības Tūre Bikses', 'Laudantium debitis ratione quos ut commodi quod omnis eligendi.', 41),
	('Pilsētas Plēve', 'Nihil error unde voluptates fuga itaque distinctio odit ipsum explicabo aperiam.', 41),
	('Bastions Zobens', 'Eos veniam a quia quas perferendis nostrum totam dignissimos odio totam velit.', 41),
	('Iešana', 'Iešana ir līdzinieks jebkura karavīra arsenālā, gatavs pārsteigt ienaidniekus.', 48),
	('Pēdējās Karalienes Maģija', 'At provident aut voluptatem consequuntur ad eaque.', 48),
	('Leģendārā Izdzīvošanas Ķirsis', NULL, 48),
	('Kalna Cepure', 'Quidem illo magni esse asperiores accusamus deserunt doloremque sit labore omnis.', 13),
	('Ķēde', 'Perferendis distinctio laborum eum impedit tempora natus beatae animi et.', 13),
	('Kaujas Āmurs', 'Doloremque labore fugiat soluta tenetur nostrum soluta dolores totam est libero.', 13),
	('Mistērijas Zirgs', NULL, 37),
	('Leģendārā Bikses', NULL, 37),
	('Lielās Bastions Tūre Ķivere', NULL, 37),
	('Iešana', 'Iešana ir līdzinieks jebkura karavīra arsenālā, gatavs pārsteigt ienaidniekus.', 37),
	('Zirgs', 'Ut fugit occaecati assumenda reiciendis aut provident quasi nisi dolore.', 37),
	('Kosmosa Cerības Pilis', NULL, 37),
	('Bastions ŅSG', 'Est voluptates harum repudiandae quo exercitationem rem labore autem voluptates.', 37),
	('Izpētītāju Ķēde', 'Deleniti aliquam consequatur blanditiis unde temporibus quis dolor doloremque vitae libero sunt nostrum.', 37),
	('Dvēseļu Pilis', NULL, 45),
	('Kalna Zirgs', 'Unde voluptatibus soluta repellat modi sunt saepe magnam.', 45),
	('Vēju Mistērijas Ķirsis', NULL, 45),
	('Lielās Cīņas M4A4', 'Magni aspernatur blanditiis suscipit necessitatibus aliquam eius nihil nesciunt minus deleniti.', 45),
	('Vētras Cepure', NULL, 45),
	('Senču Cīņas Ķivere', NULL, 45),
	('Draudzīgā Senču Paradīzes Ķēde', 'Nam quis repellat facere praesentium tenetur mollitia earum quaerat repellat totam ipsum similique.', 45),
	('Karalienes Šaržieris', 'Eius aut eaque natus ipsa facere suscipit rem omnis animi natus ipsa soluta.', 45),
	('Dvēseļu Zirgs', NULL, 45),
	('Draudzīgā Pilsētas Pasaules Zobens', 'Aliquam placeat delectus eligendi maxime magni deleniti neque necessitatibus.', 45),
	('Leģendārā Karalienes Iešana', 'Cupiditate cum quaerat perferendis molestias dignissimos.', 46),
	('Pēdējās Lāčplēša Valstības Šaržieris', 'Porro dignissimos occaecati dignissimos eius ducimus molestias non nulla.', 46),
	('Pasaules Zirgs', NULL, 44),
	('Pirātu Jaka', NULL, 51),
	('Ķirsis', 'Error quidem at doloribus culpa tenetur in.', 51),
	('Kosmosa Ķivere', 'Eos ea similique aliquid sequi deleniti officiis ipsum esse.', 24),
	('Leģendārā Vēju Plēve', NULL, 24),
	('Leģendārā Kalna Pasaules Bulta', 'Alias quae in voluptatum a eaque occaecati.', 24),
	('Pēdējās Valstības Bumba', 'Provident reprehenderit mollitia a asperiores consequuntur iure ea at eveniet.', 24),
	('Dvēseļu Ķirsis', NULL, 24),
	('Cerības Šaržieris', NULL, 24),
	('Draudzīgā Bikses', 'Ducimus culpa exercitationem quidem quia aliquid exercitationem numquam nobis.', 24),
	('Dvēseļu Reģiona Dzelzs', NULL, 24),
	('Leģendārā Jaka', NULL, 24),
	('Pēdējās Paradīzes Bikses', NULL, 24),
	('Leģendārā Cerības M4A4', 'Tempora dolorem fugit ipsum facilis in veniam sint.', 25),
	('Paradīzes Maģija', 'Officiis autem ratione cumque accusamus quia.', 25),
	('Draudzīgā Bastions Pilis', 'Vitae vero ipsum totam minus repudiandae.', 25),
	('Dvēseļu Senču Plēve', 'Unde possimus voluptates enim officiis culpa laudantium ex molestiae nihil delectus doloribus.', 25),
	('Kaujas Āmurs', 'Distinctio cupiditate veritatis velit fugiat ex asperiores tempora facere.', 50),
	('Krekls', 'Šis krekls ir izgatavots no ērtiem un izturīgiem materiāliem, lai jūs varētu ceļot ar stilu.', 50),
	('Kalna Bikses', NULL, 50),
	('Ziemeļu Cerības Šaržieris', NULL, 50),
	('Lāčplēša Pilis', NULL, 50),
	('Lielās Reģiona Bulta', 'Quae animi at reiciendis animi fugiat ipsa sit delectus sit temporibus nihil eum.', 50),
	('Lielās Pirātu Maģija', NULL, 38),
	('Draudzīgā Karalienes Zirgs', NULL, 38),
	('Reģiona Pasaules Plēve', NULL, 38),
	('Ziemeļu Lāčplēša Cepure', 'Aspernatur quae nihil atque sit mollitia itaque.', 38),
	('Izpētītāju Ķirsis', 'Aspernatur expedita quos alias delectus mollitia.', 38),
	('Meža Ķēde', NULL, 38),
	('Lielās Reģiona Meža Jaka', 'Eius dolore vero ea voluptas rem sunt voluptatem fugit consequuntur consectetur quod non.', 38),
	('Cīņas M4A4', 'Voluptates dolores eius quibusdam quod corporis quas perferendis perspiciatis.', 14),
	('Melnās Reģiona Pasaules Krekls', NULL, 14),
	('Ķirsis', NULL, 14),
	('Leģendārā Cīņas Plēve', 'Debitis numquam nam voluptatibus tempore id.', 14),
	('Lielās Vēju Izdzīvošanas Jaka', 'Voluptate harum ut provident nulla id impedit molestiae autem veniam cumque vitae maxime suscipit.', 14),
	('Pilsētas Dzelzs', NULL, 14),
	('Zobens', 'Zobens ir klasiskas cīņas simbols, spēcīgs un bīstams ierocis.', 33),
	('Draudzīgā ŅSG', NULL, 33),
	('Jūras Kaujas Āmurs', NULL, 33),
	('Pilis', 'Adipisci tempore dolor reprehenderit quaerat illo laborum unde.', 33),
	('Tūre Zirgs', NULL, 33),
	('Melnās Vēju Mistērijas Zirgs', NULL, 33),
	('Dvēseļu Mistērijas Plēve', 'Esse sit quia corporis iste ad fugiat error rerum eius.', 33),
	('Ziemeļu Karalienes Pirātu Dzelzs', NULL, 33),
	('Leģendārā Reģiona Paradīzes Ķivere', NULL, 56),
	('Jūras Tūre Dzelzs', NULL, 56),
	('Cerības Meža M4A4', NULL, 56),
	('Burvju Cerības Izdzīvošanas Kaujas Āmurs', 'Alias minus dolorem illum nobis dolorem culpa pariatur optio ullam.', 56),
	('Cerības Meža ŅSG', 'Incidunt accusamus aut vero inventore quisquam debitis dicta.', 56),
	('Pirātu Plēve', NULL, 56),
	('Melnās Kalna Bulta', 'Et aliquid consequatur voluptas rerum est vitae.', 56),
	('Pilsētas Ķēde', NULL, 56),
	('Akadēmijas Šaržieris', NULL, 56),
	('Ziemeļu Valstības Jaka', NULL, 43),
	('Vētras Pilsētas Plēve', NULL, 43),
	('Akadēmijas Izpētītāju Iešana', 'Iure accusamus beatae odio eligendi dolorum consectetur.', 43),
	('Cīņas Krekls', NULL, 43),
	('Bastions Izdzīvošanas Zobens', 'Aperiam culpa eligendi totam neque similique quaerat laboriosam fugit maiores quibusdam necessitatibus.', 43),
	('Leģendārā ŅSG', NULL, 43),
	('Burvju Pasaules Iešana', 'Dolorum optio corrupti occaecati exercitationem quaerat harum nobis facilis.', 43),
	('Burvju Meža Plēve', 'Voluptate modi corrupti soluta magnam reiciendis doloremque consequuntur incidunt quae labore corporis nulla.', 43),
	('Melnās Bumba', NULL, 43),
	('Karalienes Krekls', NULL, 43),
	('Leģendārā Plēve', NULL, 63),
	('Karalienes Pasaules Ķirsis', NULL, 63),
	('Bikses', 'Izgatavots no augstas kvalitātes sastāvdaļām, šis Bikses nodrošina lielisku atveseļošanos.', 63),
	('Cīņas Ķēde', 'Autem veniam aliquam doloremque nulla quae.', 63),
	('Bastions Paradīzes Kaujas Āmurs', 'Commodi sed dolore maxime at nostrum nemo pariatur dicta illo.', 35),
	('Zelta Bulta', 'Ducimus ab voluptatum at deleniti dolor quae exercitationem sunt accusamus distinctio.', 35),
	('Cīņas Zirgs', 'Dolor necessitatibus totam in similique consectetur aliquam aliquam impedit voluptatem maxime explicabo.', 35),
	('Melnās Pilsētas Tūre M4A4', NULL, 35),
	('Zelta Kalna Iešana', 'Placeat dolorum aliquam maiores magnam cumque officiis commodi illum omnis voluptatem ex magnam.', 35),
	('Akadēmijas Pasaules Ķivere', NULL, 35),
	('Kosmosa Kalna Kaujas Āmurs', NULL, 35),
	('Ziemeļu Pilsētas Cīņas Krekls', 'Vero mollitia aut maiores id sequi voluptates quos commodi minima.', 35),
	('Draudzīgā Reģiona ŅSG', 'Quae inventore at repudiandae neque temporibus maiores non hic tenetur modi totam architecto.', 35),
	('Zelta Tūre Pilis', NULL, 54),
	('Vētras Bastions Ķivere', NULL, 54),
	('Karalienes Plēve', 'Voluptatem qui error quia tempora ex est officia velit magni.', 54),
	('Karalienes Mistērijas Šaržieris', 'Quos modi inventore laboriosam doloribus voluptas amet eum repudiandae et cum dolore.', 54),
	('Cīņas Maģija', 'Ab illo harum exercitationem magni similique explicabo incidunt minima voluptatem distinctio a.', 54),
	('Vētras Meža Ķivere', NULL, 59),
	('Akadēmijas Bulta', 'Distinctio pariatur aspernatur voluptate architecto officiis dolore quam eaque facere.', 59),
	('Karalienes Valstības Pilis', 'Delectus iusto delectus id fugit consequuntur.', 59),
	('Cerības Pasaules Bulta', NULL, 59),
	('Jūras Ķēde', NULL, 59),
	('Cerības Plēve', NULL, 59),
	('Reģiona Pirātu Cepure', NULL, 59),
	('Bikses', 'Izgatavots no augstas kvalitātes sastāvdaļām, šis Bikses nodrošina lielisku atveseļošanos.', 59),
	('Pēdējās Mistērijas Krekls', 'Sapiente soluta quis harum pariatur nemo voluptate aliquid non quos voluptas.', 59),
	('Draudzīgā Meža Ķivere', NULL, 32),
	('Karalienes Izdzīvošanas Ķirsis', NULL, 32),
	('Ziemeļu Senču Maģija', NULL, 32),
	('Ķēde', 'Ab itaque repellat adipisci corporis officia a aliquam accusantium dignissimos delectus unde.', 32),
	('Ziemeļu Dzelzs', 'Repellendus tempore temporibus fuga a suscipit neque earum praesentium.', 32),
	('Dvēseļu Jūras Šaržieris', NULL, 32),
	('Akadēmijas Izpētītāju Jaka', 'Reprehenderit provident quisquam aliquid aliquam rerum sint eligendi iste.', 32),
	('Dvēseļu Bastions Bulta', 'Incidunt tempora beatae sunt sapiente totam nobis dolorum at fugiat quod rerum omnis.', 32),
	('Pēdējās Valstības Bikses', 'Deleniti dignissimos exercitationem deleniti dolorum in laboriosam.', 32),
	('Burvju Kalna Tūre Ķēde', 'Corporis sapiente quasi maiores odit dolor deserunt eaque facilis.', 60),
	('Burvju Bulta', NULL, 60),
	('Vētras Mistērijas Jaka', NULL, 60),
	('Dzelzs', 'Dzelzs ir būtiska materiāla sastāvdaļa daudzu ieroču un bruņu ražošanā.', 60),
	('Draudzīgā Senču Valstības Bumba', NULL, 60),
	('Pēdējās Karalienes Plēve', NULL, 16),
	('Kosmosa Valstības Zirgs', NULL, 16),
	('Pirātu M4A4', NULL, 16),
	('Vētras Vēju Valstības M4A4', NULL, 67),
	('Paradīzes Cepure', NULL, 67),
	('Draudzīgā Karalienes Meža Pilis', 'Culpa voluptatem provident repudiandae repellat laudantium.', 67),
	('Cīņas Šaržieris', 'Quos dolore alias voluptatem perspiciatis earum quidem modi.', 67),
	('Leģendārā Zobens', 'Laborum vero corrupti ipsam quia temporibus eum eius inventore explicabo placeat qui adipisci.', 69),
	('Vētras Bikses', NULL, 69),
	('Draudzīgā Kaujas Āmurs', 'Quaerat dolorum blanditiis qui dignissimos iste repellendus consectetur molestias ipsa nobis rerum.', 69),
	('Pēdējās Reģiona Plēve', NULL, 69),
	('Karalienes Izdzīvošanas Zirgs', 'Totam ullam sit consequuntur quis cumque sequi odio nam est illum velit.', 69),
	('Cerības Pasaules Ķirsis', 'Quae quaerat repellendus vel commodi quibusdam nisi nemo autem ducimus cum tempora.', 69),
	('Akadēmijas Bulta', NULL, 69),
	('Bastions Mistērijas Maģija', 'Et maxime nisi nostrum repellat numquam modi ipsa saepe minima et culpa placeat.', 69),
	('Ķēde', 'Explicabo assumenda recusandae cum quibusdam quas non doloremque quasi.', 69),
	('Pilsētas ŅSG', NULL, 69),
	('Jūras Šaržieris', 'Doloribus officiis aperiam dolorem magni enim quia omnis porro error atque praesentium.', 70),
	('Karalienes Iešana', 'Error ipsum laudantium quo veniam minima nulla esse eaque ullam.', 72),
	('Meža Jaka', 'Numquam voluptatum ex fugit praesentium repellendus quae sint sapiente eius fugiat accusantium.', 72),
	('Lielās Karalienes Bulta', 'Quod voluptatibus est perferendis maiores nesciunt temporibus rerum molestiae laudantium.', 68),
	('Jūras Šaržieris', NULL, 68),
	('Ķēde', 'Ipsam beatae quod vel eum tempore perspiciatis sapiente repellendus suscipit facere.', 68),
	('Izpētītāju Dzelzs', NULL, 68),
	('Karalienes Bikses', NULL, 68),
	('Lielās Zirgs', 'Nulla omnis ad sequi iusto nobis cupiditate voluptas.', 68),
	('Burvju Jaka', NULL, 68),
	('Leģendārā Izdzīvošanas Iešana', NULL, 68),
	('Lielās Vēju Ķēde', NULL, 68),
	('Vētras Cerības Meža Ķēde', 'Repudiandae itaque suscipit nisi ad labore autem numquam saepe laborum porro voluptatem.', 74),
	('Mistērijas Bulta', NULL, 74),
	('Kosmosa Ķirsis', NULL, 74),
	('M4A4', 'M4A4 piedāvā stabilu uguni un precīzu mērķēšanu, lai apkarotu jebkuru draudu.', 74),
	('Melnās Senču Cepure', 'Itaque nostrum nobis libero non atque quidem debitis velit veritatis ad.', 74),
	('Zelta Jūras Pirātu Ķēde', 'Eligendi ipsa reprehenderit iure autem quam quia nobis.', 49),
	('Pēdējās Senču Meža Bikses', 'Cum ipsam debitis aperiam quo aliquam nam iure.', 49),
	('Burvju Lāčplēša Ķivere', NULL, 49),
	('Meža Ķēde', 'Earum pariatur inventore qui quod laboriosam sapiente.', 49),
	('Iešana', 'Iešana ir līdzinieks jebkura karavīra arsenālā, gatavs pārsteigt ienaidniekus.', 49),
	('Šaržieris', 'Nostrum ipsum architecto nesciunt neque eligendi ducimus laudantium laudantium.', 17),
	('Melnās Krekls', 'Suscipit eum nulla porro possimus recusandae quod.', 17),
	('Bastions Bikses', NULL, 17),
	('Zelta Kalna Dzelzs', 'Eligendi quia voluptas hic fugiat pariatur repudiandae eos quas facilis temporibus odio iusto.', 17),
	('Cīņas Maģija', NULL, 17),
	('Ķirsis', NULL, 17),
	('Karalienes Valstības Bumba', NULL, 17),
	('Izdzīvošanas Ķirsis', NULL, 79),
	('Vētras Kalna Mistērijas Bikses', NULL, 79),
	('Lāčplēša Valstības Maģija', 'Maiores laudantium ad eaque exercitationem facilis quam harum voluptatem.', 62),
	('Paradīzes Ķivere', 'Provident consectetur quaerat unde praesentium voluptatum nam perspiciatis deserunt iusto enim rerum assumenda.', 62),
	('Izdzīvošanas Jaka', 'Provident doloremque repellat quasi occaecati facere corporis enim eos harum.', 62),
	('Kalna Bulta', NULL, 62),
	('Iešana', 'Iešana ir līdzinieks jebkura karavīra arsenālā, gatavs pārsteigt ienaidniekus.', 62),
	('Ķirsis', 'Aliquid nobis tempora asperiores natus dicta quos.', 62),
	('Burvju Reģiona Krekls', 'Eum quo quis sunt harum porro.', 62),
	('Paradīzes M4A4', NULL, 62),
	('Ziemeļu Cerības Zirgs', NULL, 62),
	('Meža Pilis', NULL, 75),
	('Lielās Karalienes Dzelzs', 'Numquam maxime suscipit dolorem tempore consequatur blanditiis expedita a nobis.', 75),
	('Leģendārā Cerības Mistērijas Jaka', 'Tenetur nostrum omnis dolorum repudiandae facilis quidem.', 75),
	('Akadēmijas Meža M4A4', 'Maxime laboriosam eaque saepe ullam ipsum quia expedita.', 75),
	('Bulta', 'Accusamus hic eligendi alias sit nisi quisquam velit similique nihil nisi aliquam quia corporis.', 75),
	('Burvju Vēju Maģija', 'Perspiciatis consectetur debitis laudantium ex cupiditate.', 75),
	('Burvju Bikses', NULL, 75),
	('Izpētītāju Zobens', 'Ad dolore corporis et quidem nihil repellendus rerum eaque alias illum.', 75),
	('Draudzīgā Valstības M4A4', 'Similique cum accusantium necessitatibus deserunt quis culpa adipisci.', 75),
	('Akadēmijas Bulta', NULL, 75),
	('Reģiona Zirgs', NULL, 81),
	('Akadēmijas Jaka', NULL, 73),
	('Lāčplēša Bulta', NULL, 73),
	('Pasaules Zobens', 'Rem earum veritatis architecto blanditiis rerum.', 73),
	('Pilsētas Tūre Dzelzs', NULL, 73),
	('Dvēseļu Reģiona Ķirsis', 'Et libero aspernatur nam rerum asperiores corporis quidem dignissimos.', 73),
	('Draudzīgā Jaka', NULL, 73),
	('Pilis', 'Doloremque culpa qui architecto sed hic.', 83),
	('Leģendārā Reģiona Zirgs', NULL, 83),
	('Maģija', NULL, 83),
	('Pēdējās Reģiona Pasaules Maģija', NULL, 83),
	('Lielās Pasaules Iešana', NULL, 83),
	('Lielās Ķirsis', NULL, 83),
	('Bikses', 'Izgatavots no augstas kvalitātes sastāvdaļām, šis Bikses nodrošina lielisku atveseļošanos.', 83),
	('Draudzīgā Valstības Krekls', 'Voluptatibus numquam nostrum maiores deserunt earum ipsa laborum accusantium culpa.', 83),
	('Plēve', NULL, 84),
	('Kosmosa Paradīzes Ķivere', 'Deleniti debitis consequatur atque laudantium atque qui aliquid alias officia a blanditiis.', 84),
	('Senču Valstības ŅSG', 'Cumque inventore excepturi repellendus velit dolorem.', 84),
	('Vētras Reģiona Maģija', 'Nisi asperiores harum quis rerum facilis unde blanditiis.', 85),
	('Akadēmijas Bulta', NULL, 85),
	('Vētras Vēju Kaujas Āmurs', 'Unde explicabo praesentium velit dicta similique architecto laborum vel dolorem.', 85),
	('Kalna Pilis', 'Harum fuga sunt fugiat blanditiis modi quod.', 85),
	('Zelta Krekls', 'Recusandae aperiam nobis veniam ab sint.', 90),
	('Draudzīgā Kalna Tūre Ķivere', 'Officia non harum explicabo reprehenderit doloremque aperiam accusantium quasi vel nostrum.', 90),
	('Meža Zobens', 'Exercitationem consequatur laboriosam cum sapiente quidem delectus tempora porro occaecati id eos quidem.', 90),
	('Vēju Iešana', 'Alias labore maiores alias laborum culpa laboriosam ipsam blanditiis tempora optio natus soluta.', 90),
	('Ziemeļu Maģija', 'Nemo quos iusto voluptates accusantium maiores non.', 34),
	('Kalna Ķivere', 'Sit architecto deleniti aliquid vel dolorum beatae sequi asperiores minus facere.', 34),
	('Draudzīgā Vēju Izdzīvošanas Maģija', 'Eligendi vel sit hic aspernatur ab culpa voluptatem.', 34),
	('Zelta Vēju Ķirsis', NULL, 34),
	('Zelta Lāčplēša Iešana', NULL, 34),
	('Zelta Bumba', NULL, 91),
	('Kalna Paradīzes Bulta', 'Quam explicabo dignissimos exercitationem aperiam maxime perspiciatis consequatur fuga perspiciatis nostrum repudiandae nulla.', 91),
	('Leģendārā Karalienes Tūre Bulta', 'Architecto voluptates dolore quis rem maiores quaerat at ducimus possimus adipisci inventore.', 91),
	('Dzelzs', 'Dzelzs ir būtiska materiāla sastāvdaļa daudzu ieroču un bruņu ražošanā.', 86),
	('Cīņas Ķivere', NULL, 86),
	('Ziemeļu Lāčplēša Ķivere', 'Voluptates suscipit explicabo numquam officiis cumque officia quas consequatur ipsam ullam consequuntur quas.', 86),
	('Lāčplēša Jaka', NULL, 86),
	('Vēju Ķēde', NULL, 86),
	('Melnās Reģiona Bulta', NULL, 86),
	('Kosmosa Jaka', 'Inventore reiciendis cumque ducimus ea quasi voluptas.', 57),
	('Ziemeļu Pasaules Ķivere', 'Et sint amet suscipit cumque similique cupiditate nulla ipsa repellat.', 57),
	('Vētras Valstības Pilis', 'Quis tenetur ut voluptatibus voluptatum facilis doloribus illum doloribus aperiam nihil voluptas numquam.', 57),
	('Lāčplēša Jaka', 'Est a sint atque quaerat doloremque facere consequuntur quam eos accusamus.', 57),
	('Zelta Maģija', 'Odit voluptatem ab odio totam et eaque nisi dolorem sequi dolores quasi optio.', 15),
	('Vētras Krekls', NULL, 15),
	('Leģendārā Valstības ŅSG', 'Quisquam provident earum nisi optio sint necessitatibus reprehenderit ab.', 15),
	('Karalienes Tūre Šaržieris', 'Saepe animi doloremque suscipit tempora tenetur quae nam.', 15),
	('Meža Šaržieris', 'Tempora omnis aperiam rem dicta nemo ea maiores.', 64),
	('Izdzīvošanas Zobens', NULL, 64),
	('Karalienes M4A4', 'Expedita molestias aspernatur nostrum saepe error aliquid itaque ab error.', 64),
	('Jūras Meža M4A4', 'Ab doloremque nemo quae commodi aperiam temporibus placeat sequi earum suscipit.', 64),
	('Senču Krekls', NULL, 64),
	('Melnās Tūre Bikses', NULL, 64),
	('Zelta Pasaules Zobens', 'Est dicta facere aperiam vitae eaque libero illo.', 64),
	('Izpētītāju Cepure', NULL, 64),
	('Tūre Jaka', NULL, 64),
	('Pēdējās Cīņas Jaka', 'Laborum nobis laborum vero sequi voluptatum quisquam corporis.', 64),
	('Senču Cepure', 'Corporis ipsum amet doloribus dolorem repudiandae.', 94),
	('Vēju Mistērijas Plēve', 'Voluptatum eveniet aspernatur ullam illum hic.', 94),
	('Melnās Zobens', 'Veritatis libero alias eligendi libero vitae aperiam fuga impedit omnis.', 94),
	('Kalna Tūre Ķēde', 'Impedit veritatis repellat ab ipsa odit sed tempore est nobis fuga illo.', 94),
	('Reģiona Iešana', 'Perspiciatis excepturi aspernatur harum fugiat ratione accusantium quis.', 94),
	('Pasaules Bikses', 'At molestias totam laudantium incidunt ratione ex asperiores.', 87),
	('Vēju ŅSG', NULL, 87),
	('Pēdējās Reģiona M4A4', NULL, 58),
	('Cerības Izdzīvošanas Cepure', NULL, 58),
	('Cerības Izpētītāju Kaujas Āmurs', 'Aperiam fuga nulla quibusdam totam occaecati quod molestiae eos.', 58),
	('Lielās Akadēmijas Bikses', NULL, 58),
	('Jaka', 'Šī jaka ir silta un ērta, ideāli piemērota ilgām ceļojuma dienām.', 58),
	('Lielās Cerības Zobens', NULL, 58),
	('Karalienes Valstības Bikses', 'Nemo sed placeat occaecati ex quo nesciunt cumque.', 58),
	('Zobens', 'Zobens ir klasiskas cīņas simbols, spēcīgs un bīstams ierocis.', 58),
	('Pilsētas Pirātu Maģija', 'Reprehenderit veniam rerum hic molestiae voluptatibus unde quis cumque laborum praesentium distinctio.', 99),
	('Leģendārā Senču Plēve', 'Corporis esse aliquid molestias voluptas laborum enim eaque nobis.', 99),
	('Melnās Jūras Krekls', NULL, 99),
	('Jūras Plēve', 'Tenetur minima labore amet ratione officia hic laboriosam.', 99),
	('Vētras Ķēde', 'Illo libero nobis eos totam temporibus ipsam.', 99),
	('Bikses', 'Izgatavots no augstas kvalitātes sastāvdaļām, šis Bikses nodrošina lielisku atveseļošanos.', 88),
	('Ziemeļu Iešana', NULL, 88),
	('Kosmosa Valstības M4A4', 'Nemo error architecto perspiciatis quasi sed unde repellat praesentium in quos.', 88),
	('Vēju Bikses', 'Libero iste odit delectus perspiciatis omnis rem quisquam tempora molestias corrupti.', 88),
	('Kosmosa Vēju Pasaules Krekls', NULL, 88),
	('Maģija', 'Suscipit consequatur neque velit corporis velit velit ex officiis temporibus quisquam exercitationem.', 88),
	('Šaržieris', 'Aspernatur deserunt ab nihil nesciunt architecto vitae doloremque nemo fuga ipsam.', 107),
	('Zelta Akadēmijas Izpētītāju Pilis', 'Consectetur sed quo asperiores vero ratione adipisci aut laborum ullam tempore.', 107),
	('Ķēde', 'Mollitia tenetur tempore harum dolor eum libero blanditiis quis dolore sequi officiis.', 107),
	('Lāčplēša Izdzīvošanas Ķivere', 'Vitae enim quaerat ducimus veritatis id sed consectetur numquam.', 95),
	('Melnās Vēju Tūre Šaržieris', NULL, 95),
	('Melnās Jūras Šaržieris', NULL, 95),
	('Leģendārā Pasaules Ķivere', NULL, 95),
	('Zobens', 'Zobens ir klasiskas cīņas simbols, spēcīgs un bīstams ierocis.', 95),
	('Cerības Maģija', 'Amet harum voluptas asperiores repudiandae qui veniam.', 95),
	('Burvju Vēju Krekls', 'Eos nobis eum tempora dolores incidunt quia iusto maiores excepturi a eum.', 95),
	('Krekls', 'Šis krekls ir izgatavots no ērtiem un izturīgiem materiāliem, lai jūs varētu ceļot ar stilu.', 95),
	('Draudzīgā Cerības Ķēde', NULL, 95),
	('Dvēseļu Vēju Izpētītāju Bulta', 'Iste iste necessitatibus ab molestias iusto.', 65),
	('Senču Valstības Plēve', NULL, 65),
	('Pēdējās Vēju Pilis', NULL, 65),
	('Melnās Karalienes M4A4', NULL, 65),
	('Melnās Valstības M4A4', NULL, 96),
	('Karalienes Zirgs', NULL, 96),
	('Vētras Pirātu Zobens', NULL, 102),
	('Kalna Bulta', NULL, 102),
	('Zelta Pirātu Jaka', 'Harum ut quos possimus delectus itaque id.', 102),
	('Senču Izdzīvošanas Maģija', NULL, 102),
	('Ziemeļu Pilsētas Maģija', NULL, 105),
	('Kalna ŅSG', 'Ex perspiciatis asperiores doloribus harum quisquam molestias.', 105),
	('Vētras Reģiona Ķēde', NULL, 105),
	('Zelta Pilsētas Izpētītāju Maģija', 'Dolor et quam natus sed quidem et deserunt.', 105),
	('Jūras Cepure', 'Optio similique exercitationem eveniet nesciunt nihil voluptas exercitationem at earum porro.', 105),
	('Cerības Maģija', NULL, 105),
	('Reģiona M4A4', 'Aliquam eum exercitationem ullam sit inventore consequatur dolorum dolorum sapiente.', 105),
	('Burvju Pirātu Šaržieris', 'Quos adipisci deleniti quibusdam atque cumque minima magnam eos deserunt qui tempora.', 78),
	('Melnās Jūras Pirātu Ķirsis', NULL, 78),
	('Krekls', 'Šis krekls ir izgatavots no ērtiem un izturīgiem materiāliem, lai jūs varētu ceļot ar stilu.', 78),
	('Zelta Valstības Bumba', 'Earum temporibus repudiandae occaecati fugiat dicta animi sint quo debitis.', 78),
	('Lielās Pilsētas Ķēde', NULL, 98),
	('Dvēseļu Pilsētas Pilis', NULL, 98),
	('Reģiona Pirātu Plēve', 'Tempore minima in ea recusandae necessitatibus rerum aliquid maiores ullam debitis earum.', 98),
	('Pilsētas Cepure', 'Nulla quod reprehenderit blanditiis sunt occaecati nobis maiores quae culpa.', 98),
	('Ķēde', 'Pariatur nesciunt doloribus doloribus assumenda veritatis deserunt delectus alias sint corporis.', 98),
	('Reģiona Cepure', 'Ratione voluptate tempora saepe quam rerum molestias provident eius occaecati.', 98),
	('Mistērijas Dzelzs', 'Impedit eligendi optio ducimus voluptatem quos expedita consequatur quia fuga architecto alias sint.', 89),
	('Reģiona Kaujas Āmurs', 'Velit ad dolores harum sequi sunt earum perferendis ducimus.', 89),
	('Vēju Izdzīvošanas Iešana', 'Atque officiis impedit esse perferendis esse deleniti.', 89),
	('Draudzīgā Bumba', NULL, 89),
	('Jaka', 'Šī jaka ir silta un ērta, ideāli piemērota ilgām ceļojuma dienām.', 101),
	('Paradīzes Ķivere', 'Sequi nemo amet tenetur delectus earum reiciendis officia eos id quas esse ducimus.', 101),
	('Pasaules Krekls', NULL, 101),
	('Cerības Meža M4A4', 'Nesciunt velit quia neque at nam deleniti iusto non quibusdam beatae dicta repellat.', 101),
	('Ziemeļu Iešana', 'Facere officia natus dolor vitae debitis accusantium perferendis sed.', 101),
	('Ziemeļu Mistērijas Zobens', 'Fuga voluptatem eaque repudiandae dolor enim ipsam aspernatur.', 101),
	('Senču Valstības Iešana', NULL, 101),
	('Reģiona Maģija', NULL, 101),
	('Kalna Valstības Šaržieris', 'Eligendi praesentium ad aliquam fugiat labore quod repellendus repellat animi.', 101),
	('Leģendārā Lāčplēša Izdzīvošanas Dzelzs', 'Aut debitis repellendus aperiam dolorum illum sint fugit quod optio amet.', 101),
	('Kalna ŅSG', 'Ea ipsa cum ut distinctio quasi vero ab nesciunt consequuntur quaerat iusto.', 106),
	('Akadēmijas ŅSG', 'Dolores blanditiis cumque quisquam harum dolor rerum.', 106),
	('Reģiona Jaka', 'Laborum quam dolorum dolorem iste rerum molestiae recusandae beatae libero.', 106),
	('Vētras Tūre Cepure', 'Perferendis architecto optio dolorem reprehenderit voluptas iusto dolor atque nisi.', 77),
	('Zirgs', NULL, 77),
	('Dvēseļu Izpētītāju Bikses', NULL, 77),
	('Krekls', 'Šis krekls ir izgatavots no ērtiem un izturīgiem materiāliem, lai jūs varētu ceļot ar stilu.', 77),
	('Vēju M4A4', NULL, 77),
	('Karalienes Valstības Bikses', 'In doloribus vel voluptate quia unde inventore amet quia illo quam.', 77),
	('Pilsētas ŅSG', 'Mollitia vitae quisquam aperiam fugit dignissimos.', 77),
	('Valstības Ķirsis', NULL, 77),
	('Vēju Bumba', 'Fugit autem non officiis quasi odit consequuntur voluptate nostrum.', 77),
	('Zelta Akadēmijas Pirātu Jaka', 'Doloribus sapiente ea voluptatibus consequuntur a recusandae soluta fuga.', 108),
	('Burvju Lāčplēša Pirātu Dzelzs', NULL, 108),
	('Ziemeļu Senču Dzelzs', NULL, 108),
	('Vētras Reģiona Izpētītāju Dzelzs', NULL, 108),
	('Lāčplēša Ķēde', 'Magni voluptatem quas eaque reiciendis dolorem.', 109),
	('Bastions Plēve', NULL, 109),
	('Šaržieris', NULL, 109),
	('Burvju Meža Zirgs', 'Adipisci maiores nulla deleniti officia beatae aspernatur harum perferendis earum excepturi.', 109),
	('Jūras Jaka', 'Ducimus assumenda officiis illum odio explicabo velit impedit doloribus cupiditate repudiandae.', 109),
	('Vēju Krekls', 'Repellendus praesentium incidunt quibusdam qui nam aperiam quae doloribus quas quo sit.', 109),
	('Vēju Tūre Kaujas Āmurs', NULL, 109),
	('Plēve', 'Natus beatae illo fugit nesciunt quos minus deserunt praesentium atque.', 109),
	('Jūras Pirātu Zobens', 'Facilis reprehenderit vitae vel architecto ducimus ab minus esse mollitia perspiciatis omnis expedita.', 109),
	('Plēve', 'Id magnam asperiores perferendis dolores sed.', 109),
	('Tūre Jaka', 'Explicabo facilis dolor explicabo iusto voluptatum omnis.', 104),
	('Melnās M4A4', 'Neque placeat eligendi nam deserunt magni pariatur vel accusantium nostrum.', 104),
	('Karalienes Zobens', 'Nobis fugit quod libero perferendis perspiciatis eligendi molestias aliquid.', 104),
	('Melnās Lāčplēša Pirātu Ķēde', 'Unde corrupti laborum facilis alias placeat porro aliquid harum veniam.', 104),
	('Burvju Šaržieris', 'Fuga ducimus magnam maxime consectetur nostrum dolorem.', 113),
	('Draudzīgā Pilsētas Bikses', NULL, 113),
	('Dzelzs', 'Dzelzs ir būtiska materiāla sastāvdaļa daudzu ieroču un bruņu ražošanā.', 97),
	('Ķēde', NULL, 97),
	('Senču Plēve', 'Harum maxime consequatur dolores vel nam accusantium rerum nam optio labore temporibus.', 97),
	('Maģija', 'Sed adipisci assumenda quod rerum et repellat natus.', 97),
	('Lielās Meža Iešana', NULL, 97),
	('Izdzīvošanas Bikses', NULL, 97),
	('Pilsētas Pirātu Cepure', 'Laudantium maiores accusamus quo dicta blanditiis.', 97),
	('Vētras Kalna Mistērijas Maģija', 'Ipsum temporibus deleniti accusamus rem cumque vero.', 97),
	('Dvēseļu Kalna Paradīzes Plēve', 'Molestiae nihil asperiores amet accusantium beatae cupiditate nam magnam nisi non hic.', 97),
	('Kosmosa Akadēmijas Zirgs', 'Alias culpa delectus fugiat quis enim repellendus tempora odio.', 117),
	('Tūre M4A4', NULL, 117),
	('Kosmosa Pilsētas Bikses', 'Iste impedit nihil laboriosam libero dolore aliquam.', 117),
	('Senču Pirātu M4A4', 'Quidem rerum iure adipisci provident laboriosam.', 117),
	('Zelta Reģiona Krekls', NULL, 117),
	('Kaujas Āmurs', 'Rerum eos rerum perferendis nam nesciunt ducimus vero adipisci suscipit.', 118),
	('Leģendārā Reģiona Tūre Šaržieris', NULL, 118),
	('Vētras Senču Meža Ķivere', NULL, 118),
	('Zelta Valstības Krekls', 'At placeat autem qui dicta illo laudantium voluptas eius repellendus earum nulla.', 118),
	('Kalna Pilis', NULL, 118),
	('ŅSG', 'Ar precīzu mērķēšanu un lielu kaitējumu, ŅSG ir perfekta izvēle cīņai.', 118),
	('Kosmosa Paradīzes ŅSG', 'Tempore possimus ratione harum id autem earum.', 118),
	('Kosmosa Cerības Izpētītāju Maģija', 'Provident tempora hic velit corporis non dignissimos natus.', 112),
	('Ziemeļu Karalienes Dzelzs', NULL, 112),
	('ŅSG', 'Ar precīzu mērķēšanu un lielu kaitējumu, ŅSG ir perfekta izvēle cīņai.', 112),
	('Mistērijas Pilis', 'Cumque tempora qui dolorum distinctio inventore libero veritatis.', 112),
	('Kosmosa Lāčplēša Pilis', NULL, 42),
	('Kosmosa Pirātu Krekls', 'Quisquam corrupti vitae vel temporibus eaque.', 42),
	('Leģendārā Jaka', 'Voluptatum non numquam recusandae eum maxime.', 42),
	('Draudzīgā Kalna Izdzīvošanas Krekls', NULL, 42),
	('Zelta Kalna Tūre Zobens', NULL, 42),
	('Burvju Reģiona Ķivere', 'Accusantium non tenetur rem ad provident quaerat.', 42),
	('Dvēseļu Dzelzs', 'Consequatur illo labore totam non vel iure neque error dolores nemo similique.', 42),
	('Senču M4A4', 'Aperiam iure voluptates eius qui excepturi praesentium.', 42),
	('Zelta Šaržieris', NULL, 42),
	('Ķēde', NULL, 111),
	('Dvēseļu Vēju Bumba', NULL, 111),
	('Pasaules ŅSG', 'Debitis ullam aperiam accusantium neque laboriosam maiores exercitationem impedit architecto veritatis.', 111),
	('Karalienes Dzelzs', NULL, 119),
	('Kosmosa Reģiona Plēve', 'Quae dolor repudiandae voluptatem laboriosam ut quas aut nobis doloribus.', 119),
	('Pēdējās Reģiona Cīņas Šaržieris', 'Deleniti repellat ad libero veritatis vitae commodi fugit ipsum distinctio eveniet atque debitis.', 119),
	('Burvju Zobens', NULL, 119),
	('Bulta', 'Iusto vitae blanditiis amet officia similique modi quod incidunt commodi quam et perspiciatis.', 119);