INSERT INTO SpēleŽanrs (SpēleID, ŽanrsNosaukums) VALUES 
	(1, 'Asa sižeta'),
	(1, 'FPS'),
	(1, 'Multiplayer'),
	(1, 'Šautene'),
	(1, 'Sacensību'),
	(1, 'Taktiskā'),
	(1, 'Vecā skola'),
	(1, 'Stratēģija'),
	(1, 'Izdzīvošana'),
	(2, 'Asa sižeta'),
	(2, 'FPS'),
	(2, 'Multiplayer'),
	(2, 'Šautene'),
	(2, 'Vecā skola'),
	(2, 'Co-op'),
	(2, 'Sacensību'),
	(2, 'Retro'),
	(3, 'Asa sižeta'),
	(3, 'FPS'),
	(3, 'Multiplayer'),
	(3, 'Zinātniskā fantastika'),
	(3, 'Šautene'),
	(3, 'Kosmosā'),
	(3, 'Kiberpanks'),
	(3, 'Platformas spēle'),
	(3, '3D'),
	(3, 'Vecā skola'),
	(3, 'Retro'),
	(3, 'Sacensību'),
	(3, 'Sports'),
	(4, 'FPS'),
	(4, 'Zinātniskā fantastika'),
	(4, 'Multiplayer'),
	(4, 'Viena spēlētāja'),
	(4, 'Asa sižeta'),
	(4, 'Šautene'),
	(4, 'Bagāts stāsts'),
	(4, 'Atmosfēriska'),
	(4, 'Piedzīvojumu'),
	(4, 'Retro'),
	(5, 'FPS'),
	(5, 'Asa sižeta'),
	(5, 'Zinātniskā fantastika'),
	(5, 'Viena spēlētāja'),
	(5, 'Bagāts stāsts'),
	(5, 'Šautene'),
	(5, 'Piedzīvojumu'),
	(5, 'Atmosfēriska'),
	(5, 'Zombiji'),
	(5, 'Šausmu'),
	(5, 'Puzzle'),
	(5, 'Multiplayer'),
	(6, 'Šautene'),
	(6, 'Asa sižeta'),
	(6, 'FPS'),
	(6, 'Multiplayer'),
	(6, 'Taktiskā'),
	(6, 'Sacensību'),
	(6, 'Karš'),
	(6, 'Stratēģija'),
	(6, 'Viena spēlētāja'),
	(6, 'Atmosfēriska'),
	(6, 'Izdzīvošana'),
	(6, 'Simulācija'),
	(6, 'Sandbox'),
	(7, 'FPS'),
	(7, 'Asa sižeta'),
	(7, 'Viena spēlētāja'),
	(7, 'Zinātniskā fantastika'),
	(7, 'Šautene'),
	(7, 'Piedzīvojumu'),
	(7, 'Atmosfēriska'),
	(7, 'Multiplayer'),
	(7, 'Postapokaliptisks'),
	(7, 'Bagāts stāsts'),
	(8, 'Asa sižeta'),
	(8, 'FPS'),
	(8, 'Multiplayer'),
	(8, 'Šautene'),
	(8, 'Zinātniskā fantastika'),
	(8, 'Piedzīvojumu'),
	(8, 'Sacensību'),
	(8, 'Šausmu'),
	(8, 'Atmosfēriska'),
	(8, 'Viena spēlētāja'),
	(9, 'FPS'),
	(9, 'Asa sižeta'),
	(9, 'Zinātniskā fantastika'),
	(9, 'Viena spēlētāja'),
	(9, 'Bagāts stāsts'),
	(9, 'Šautene'),
	(9, 'Piedzīvojumu'),
	(9, 'Zombiji'),
	(9, 'Atmosfēriska'),
	(9, 'Puzzle'),
	(10, 'Puzzle'),
	(10, 'Viena spēlētāja'),
	(10, 'Zinātniskā fantastika'),
	(10, 'Komēdija'),
	(10, 'Asa sižeta'),
	(10, 'Bagāts stāsts'),
	(10, 'Platformas spēle'),
	(10, 'Atmosfēriska'),
	(10, 'FPS'),
	(10, 'Piedzīvojumu'),
	(11, 'FPS'),
	(11, 'Asa sižeta'),
	(11, 'Zinātniskā fantastika'),
	(11, 'Viena spēlētāja'),
	(11, 'Šautene'),
	(11, 'Bagāts stāsts'),
	(11, 'Piedzīvojumu'),
	(11, 'Atmosfēriska'),
	(11, 'Zombiji'),
	(11, 'Postapokaliptisks'),
	(11, 'Puzzle'),
	(11, 'Šausmu'),
	(11, 'Multiplayer'),
	(12, 'Multiplayer'),
	(12, 'FPS'),
	(12, 'Šautene'),
	(12, 'Asa sižeta'),
	(12, 'Sacensību'),
	(12, 'Co-op'),
	(12, 'Komēdija'),
	(12, 'Taktiskā'),
	(12, 'Amatniecība'),
	(13, 'Zombiji'),
	(13, 'Co-op'),
	(13, 'Multiplayer'),
	(13, 'FPS'),
	(13, 'Asa sižeta'),
	(13, 'Šausmu'),
	(13, 'Šautene'),
	(13, 'Izdzīvošana'),
	(13, 'Postapokaliptisks'),
	(13, 'Viena spēlētāja'),
	(13, 'Atmosfēriska'),
	(13, 'Piedzīvojumu'),
	(13, 'Taktiskā'),
	(13, 'Sacensību'),
	(14, 'Zombiji'),
	(14, 'Co-op'),
	(14, 'FPS'),
	(14, 'Multiplayer'),
	(14, 'Šautene'),
	(14, 'Asa sižeta'),
	(14, 'Izdzīvošana'),
	(14, 'Šausmu'),
	(14, 'Postapokaliptisks'),
	(14, 'Viena spēlētāja'),
	(14, 'Piedzīvojumu'),
	(14, 'Vietējā sadarbība'),
	(14, 'Taktiskā'),
	(15, 'MOBA'),
	(15, 'Multiplayer'),
	(15, 'Stratēģija'),
	(15, 'Sacensību'),
	(15, 'Asa sižeta'),
	(15, 'Co-op'),
	(15, 'RTS'),
	(15, 'RPG'),
	(15, 'Fantāzija'),
	(15, 'Simulācija'),
	(16, 'Platformas spēle'),
	(16, 'Puzzle'),
	(16, 'Bagāts stāsts'),
	(16, 'Asa sižeta'),
	(16, 'FPS'),
	(16, 'Co-op'),
	(16, 'Zinātniskā fantastika'),
	(16, 'Atmosfēriska'),
	(16, 'Komēdija'),
	(16, 'Piedzīvojumu'),
	(17, 'FPS'),
	(17, 'Šautene'),
	(17, 'Multiplayer'),
	(17, 'Sacensību'),
	(17, 'Asa sižeta'),
	(17, 'Taktiskā'),
	(17, 'Co-op'),
	(17, 'Stratēģija'),
	(17, 'Karš'),
	(17, 'Reālistisks'),
	(18, 'Asa sižeta'),
	(18, 'Otrais pasaules karš'),
	(18, 'FPS'),
	(18, 'Multiplayer'),
	(18, 'Viena spēlētāja'),
	(18, 'Šautene'),
	(18, 'Karš'),
	(18, 'Vēsturisks'),
	(18, 'Atmosfēriska'),
	(18, 'Bagāts stāsts'),
	(18, 'Co-op'),
	(18, 'Piedzīvojumu'),
	(18, 'Casual'),
	(18, 'Zombiji'),
	(18, 'Simulācija'),
	(19, 'Zombiji'),
	(19, 'Stratēģija'),
	(19, 'Viena spēlētāja'),
	(19, 'Casual'),
	(19, 'Komēdija'),
	(19, '2D'),
	(19, 'Puzzle'),
	(19, 'Izdzīvošana'),
	(19, 'Indie'),
	(19, 'Taktiskā'),
	(19, 'Piedzīvojumu'),
	(19, 'Postapokaliptisks'),
	(20, 'Stratēģija'),
	(20, 'Gājieniem balstīta'),
	(20, 'Vēsturisks'),
	(20, 'Multiplayer'),
	(20, 'Viena spēlētāja'),
	(20, 'Simulācija'),
	(20, 'Karš'),
	(20, 'Taktiskā'),
	(20, 'Vadība'),
	(21, 'Sandbox'),
	(21, 'Multiplayer'),
	(21, 'Būvēšana'),
	(21, 'Komēdija'),
	(21, 'Co-op'),
	(21, 'Simulācija'),
	(21, 'FPS'),
	(21, 'Viena spēlētāja'),
	(21, 'Asa sižeta'),
	(21, 'Šautene'),
	(21, 'Indie'),
	(21, 'Piedzīvojumu'),
	(22, 'Atmosfēriska'),
	(22, 'Postapokaliptisks'),
	(22, 'Atvērtā pasaule'),
	(22, 'FPS'),
	(22, 'Izdzīvošana'),
	(22, 'Asa sižeta'),
	(22, 'RPG'),
	(22, 'Šautene'),
	(22, 'Šausmu'),
	(22, 'Viena spēlētāja'),
	(22, 'Piedzīvojumu'),
	(22, 'Zinātniskā fantastika'),
	(23, 'Stratēģija'),
	(23, 'RTS'),
	(23, 'Zinātniskā fantastika'),
	(23, 'Multiplayer'),
	(23, 'Reālā laika'),
	(23, 'Taktiskā'),
	(23, 'Viena spēlētāja'),
	(23, 'Karš'),
	(23, 'Asa sižeta'),
	(23, 'Fantāzija'),
	(23, 'Bagāts stāsts'),
	(24, 'FPS'),
	(24, 'Asa sižeta'),
	(24, 'Taktiskā'),
	(24, 'Zinātniskā fantastika'),
	(24, 'Viena spēlētāja'),
	(24, 'Šautene'),
	(24, 'Multiplayer'),
	(24, 'Atmosfēriska'),
	(24, 'Kosmosā'),
	(24, 'Piedzīvojumu'),
	(24, 'Karš'),
	(24, 'Co-op'),
	(24, 'Stratēģija'),
	(25, 'Asa sižeta'),
	(25, 'Multiplayer'),
	(25, 'Šautene'),
	(25, 'Zinātniskā fantastika'),
	(25, 'Kosmosā'),
	(25, 'FPS'),
	(25, 'Viena spēlētāja'),
	(25, 'Co-op'),
	(25, 'Taktiskā'),
	(25, 'Stratēģija'),
	(25, 'Piedzīvojumu'),
	(26, 'Maskēšanās'),
	(26, 'Asa sižeta'),
	(26, 'Viena spēlētāja'),
	(26, 'Šautene'),
	(26, 'Sandbox'),
	(26, 'Vecā skola'),
	(26, 'Piedzīvojumu'),
	(26, 'FPS'),
	(26, 'Atmosfēriska'),
	(26, 'Taktiskā'),
	(26, 'Bagāts stāsts'),
	(27, 'Maskēšanās'),
	(27, 'Asa sižeta'),
	(27, 'Viena spēlētāja'),
	(27, 'Sandbox'),
	(27, 'Puzzle'),
	(27, 'Šautene'),
	(27, 'Atmosfēriska'),
	(27, 'Stratēģija'),
	(27, 'Simulācija'),
	(28, 'Asa sižeta'),
	(28, 'Atvērtā pasaule'),
	(28, 'Šautene'),
	(28, 'Viena spēlētāja'),
	(28, 'Piedzīvojumu'),
	(28, 'Sandbox'),
	(28, 'Multiplayer'),
	(28, 'Atmosfēriska'),
	(28, 'RPG'),
	(29, 'Kiberpanks'),
	(29, 'RPG'),
	(29, 'Maskēšanās'),
	(29, 'FPS'),
	(29, 'Zinātniskā fantastika'),
	(29, 'Asa sižeta'),
	(29, 'Viena spēlētāja'),
	(29, 'Bagāts stāsts'),
	(29, 'Atmosfēriska'),
	(29, 'Šautene'),
	(30, 'FPS'),
	(30, 'Atmosfēriska'),
	(30, 'Bagāts stāsts'),
	(30, 'Asa sižeta'),
	(30, 'Viena spēlētāja'),
	(30, 'Šausmu'),
	(30, 'Šautene'),
	(30, 'Zinātniskā fantastika'),
	(30, 'RPG'),
	(30, 'Piedzīvojumu'),
	(31, 'FPS'),
	(31, 'Asa sižeta'),
	(31, 'Multiplayer'),
	(31, 'Šautene'),
	(31, 'Viena spēlētāja'),
	(31, 'Karš'),
	(31, 'Bagāts stāsts'),
	(31, 'Co-op'),
	(31, 'Atmosfēriska'),
	(31, 'Sacensību'),
	(31, 'Zombiji'),
	(32, 'Kosmosā'),
	(32, 'RPG'),
	(32, 'Zinātniskā fantastika'),
	(32, 'Atvērtā pasaule'),
	(32, 'Sandbox'),
	(32, 'Stratēģija'),
	(32, 'Multiplayer'),
	(32, 'Asa sižeta'),
	(32, 'Izpētīšana'),
	(32, 'Karš'),
	(32, 'MMORPG'),
	(32, 'PvE'),
	(33, 'FPS'),
	(33, 'Asa sižeta'),
	(33, 'Viena spēlētāja'),
	(33, 'Atmosfēriska'),
	(33, 'Bagāts stāsts'),
	(33, 'Šausmu'),
	(33, 'Šautene'),
	(33, 'Zinātniskā fantastika'),
	(33, 'Multiplayer'),
	(33, 'Piedzīvojumu'),
	(33, 'RPG'),
	(34, 'FPS'),
	(34, 'Bagāts stāsts'),
	(34, 'Asa sižeta'),
	(34, 'Viena spēlētāja'),
	(34, 'Atmosfēriska'),
	(34, 'Šautene'),
	(34, 'Skaists'),
	(34, 'Piedzīvojumu'),
	(34, 'Zinātniskā fantastika'),
	(34, 'Fantāzija'),
	(34, 'RPG'),
	(35, 'Stratēģija'),
	(35, 'Gājieniem balstīta'),
	(35, 'Multiplayer'),
	(35, 'Vēsturisks'),
	(35, 'Viena spēlētāja'),
	(35, 'Co-op'),
	(35, 'Taktiskā'),
	(35, 'Simulācija'),
	(36, 'FPS'),
	(36, 'Co-op'),
	(36, 'RPG'),
	(36, 'Asa sižeta'),
	(36, 'Loot'),
	(36, 'Šautene'),
	(36, 'Atvērtā pasaule'),
	(36, 'Komēdija'),
	(36, 'Multiplayer'),
	(36, 'Zinātniskā fantastika'),
	(36, 'Postapokaliptisks'),
	(36, 'Viena spēlētāja'),
	(36, 'Piedzīvojumu'),
	(37, 'Zombiji'),
	(37, 'Otrais pasaules karš'),
	(37, 'FPS'),
	(37, 'Multiplayer'),
	(37, 'Asa sižeta'),
	(37, 'Šautene'),
	(37, 'Co-op'),
	(37, 'Viena spēlētāja'),
	(37, 'Karš'),
	(37, 'Vēsturisks'),
	(37, 'Izdzīvošana'),
	(37, 'Šausmu'),
	(37, 'Piedzīvojumu'),
	(38, 'Asa sižeta'),
	(38, 'FPS'),
	(38, 'Multiplayer'),
	(38, 'Šautene'),
	(38, 'Viena spēlētāja'),
	(38, 'Karš'),
	(38, 'Co-op'),
	(38, 'Bagāts stāsts'),
	(38, 'Atmosfēriska'),
	(38, 'Piedzīvojumu'),
	(38, 'Taktiskā'),
	(38, 'Stratēģija'),
	(39, 'Atvērtā pasaule'),
	(39, 'Asa sižeta'),
	(39, 'Viena spēlētāja'),
	(39, 'Sandbox'),
	(39, 'Šautene'),
	(39, 'Piedzīvojumu'),
	(39, 'Atmosfēriska'),
	(39, 'Bagāts stāsts'),
	(39, 'Multiplayer'),
	(40, 'Atvērtā pasaule'),
	(40, 'Asa sižeta'),
	(40, 'Viena spēlētāja'),
	(40, 'Sandbox'),
	(40, 'Atmosfēriska'),
	(40, 'Šautene'),
	(40, 'Piedzīvojumu'),
	(40, 'Mūzika'),
	(40, 'Multiplayer'),
	(41, 'Atvērtā pasaule'),
	(41, 'Asa sižeta'),
	(41, 'Viena spēlētāja'),
	(41, 'Multiplayer'),
	(41, 'Šautene'),
	(41, 'Bagāts stāsts'),
	(41, 'Piedzīvojumu'),
	(41, 'Sandbox'),
	(41, 'Atmosfēriska'),
	(41, 'Komēdija'),
	(42, 'Atvērtā pasaule'),
	(42, 'Asa sižeta'),
	(42, 'Multiplayer'),
	(42, 'Piedzīvojumu'),
	(42, 'Viena spēlētāja'),
	(42, 'Sandbox'),
	(42, 'Šautene'),
	(42, 'Atmosfēriska'),
	(42, 'Co-op'),
	(43, 'Atvērtā pasaule'),
	(43, 'Asa sižeta'),
	(43, 'Multiplayer'),
	(43, 'Piedzīvojumu'),
	(43, 'Šautene'),
	(43, 'Sandbox'),
	(43, 'Viena spēlētāja'),
	(43, 'Kailums'),
	(43, 'Bagāts stāsts'),
	(43, 'Sacīkšu'),
	(43, 'Komēdija'),
	(43, 'Atmosfēriska'),
	(44, 'Izpētīšana'),
	(44, 'Viena spēlētāja'),
	(44, 'Platformas spēle'),
	(44, 'Puzzle'),
	(44, 'Kiberpanks'),
	(44, 'Asa sižeta'),
	(44, 'Atmosfēriska'),
	(44, 'Zinātniskā fantastika'),
	(44, 'Piedzīvojumu'),
	(45, 'Sacīkšu'),
	(45, 'Atvērtā pasaule'),
	(45, 'Multiplayer'),
	(45, 'Asa sižeta'),
	(45, 'Viena spēlētāja'),
	(45, 'Simulācija'),
	(45, 'Bagāts stāsts'),
	(46, 'RPG'),
	(46, 'Zinātniskā fantastika'),
	(46, 'Bagāts stāsts'),
	(46, 'Asa sižeta'),
	(46, 'Kosmosā'),
	(46, 'Viena spēlētāja'),
	(46, 'Izvēlei ir nozīme'),
	(46, 'Šautene'),
	(46, 'Piedzīvojumu'),
	(46, 'Atmosfēriska'),
	(46, 'Atvērtā pasaule'),
	(47, 'Šausmu'),
	(47, 'Zinātniskā fantastika'),
	(47, 'Asa sižeta'),
	(47, 'Kosmosā'),
	(47, 'Atmosfēriska'),
	(47, 'Viena spēlētāja'),
	(47, 'Šautene'),
	(47, 'Bagāts stāsts'),
	(47, 'Izdzīvošana'),
	(47, 'Piedzīvojumu'),
	(47, 'Zombiji'),
	(48, 'RPG'),
	(48, 'Fantāzija'),
	(48, 'Bagāts stāsts'),
	(48, 'Viena spēlētāja'),
	(48, 'Izvēlei ir nozīme'),
	(48, 'Asa sižeta'),
	(48, 'Kailums'),
	(48, 'Piedzīvojumu'),
	(48, 'Atmosfēriska'),
	(48, 'Atvērtā pasaule'),
	(48, 'Viduslaiku'),
	(49, 'RPG'),
	(49, 'Fantāzija'),
	(49, 'Bagāts stāsts'),
	(49, 'Izvēlei ir nozīme'),
	(49, 'Viena spēlētāja'),
	(49, 'Piedzīvojumu'),
	(49, 'Kailums'),
	(49, 'Asa sižeta'),
	(49, 'Atvērtā pasaule'),
	(49, 'Atmosfēriska'),
	(49, 'Viduslaiku'),
	(50, 'Asa sižeta'),
	(50, 'Zombiji'),
	(50, 'Co-op'),
	(50, 'Šausmu'),
	(50, 'Piedzīvojumu'),
	(50, 'Multiplayer'),
	(50, 'Šautene'),
	(50, 'Viena spēlētāja'),
	(50, 'Vietējā sadarbība'),
	(50, 'Izdzīvošana'),
	(50, 'Atmosfēriska'),
	(51, 'RPG'),
	(51, 'Atvērtā pasaule'),
	(51, 'Fantāzija'),
	(51, 'Viena spēlētāja'),
	(51, 'Piedzīvojumu'),
	(51, 'Atmosfēriska'),
	(51, 'Izpētīšana'),
	(51, 'Bagāts stāsts'),
	(51, 'Sandbox'),
	(51, 'Viduslaiku'),
	(51, 'Asa sižeta'),
	(52, 'RPG'),
	(52, 'Atvērtā pasaule'),
	(52, 'Fantāzija'),
	(52, 'Viena spēlētāja'),
	(52, 'Piedzīvojumu'),
	(52, 'Izpētīšana'),
	(52, 'Asa sižeta'),
	(52, 'Bagāts stāsts'),
	(52, 'Atmosfēriska'),
	(52, 'Viduslaiku'),
	(52, 'Sandbox'),
	(53, 'Atvērtā pasaule'),
	(53, 'RPG'),
	(53, 'Postapokaliptisks'),
	(53, 'Viena spēlētāja'),
	(53, 'Bagāts stāsts'),
	(53, 'Izpētīšana'),
	(53, 'Asa sižeta'),
	(53, 'Piedzīvojumu'),
	(53, 'Zinātniskā fantastika'),
	(53, 'FPS'),
	(53, 'Atmosfēriska'),
	(53, 'Izdzīvošana'),
	(53, 'Sandbox'),
	(53, 'Šautene'),
	(54, 'Casual'),
	(54, 'Komēdija'),
	(54, 'Viena spēlētāja'),
	(54, 'Stratēģija'),
	(54, 'Sports'),
	(54, 'Simulācija'),
	(54, 'Indie'),
	(54, 'Multiplayer'),
	(54, 'Asa sižeta'),
	(55, 'RPG'),
	(55, 'Zinātniskā fantastika'),
	(55, 'Bagāts stāsts'),
	(55, 'Viena spēlētāja'),
	(55, 'Piedzīvojumu'),
	(55, 'Izvēlei ir nozīme'),
	(55, 'Asa sižeta'),
	(55, 'Kosmosā'),
	(55, 'Izpētīšana'),
	(55, 'Fantāzija'),
	(55, 'Atmosfēriska'),
	(55, 'Gājieniem balstīta'),
	(55, 'Atvērtā pasaule'),
	(56, 'Asa sižeta'),
	(56, 'Atvērtā pasaule'),
	(56, 'Piedzīvojumu'),
	(56, 'Maskēšanās'),
	(56, 'Vēsturisks'),
	(56, 'Bagāts stāsts'),
	(56, 'Viena spēlētāja'),
	(56, 'Atmosfēriska'),
	(56, 'Multiplayer'),
	(56, 'Sandbox'),
	(56, 'Zinātniskā fantastika'),
	(57, 'JRPG'),
	(57, 'RPG'),
	(57, 'Gājieniem balstīta'),
	(57, 'Bagāts stāsts'),
	(57, 'Viena spēlētāja'),
	(57, 'Fantāzija'),
	(57, 'Retro'),
	(57, 'Piedzīvojumu'),
	(57, 'Zinātniskā fantastika'),
	(57, 'Atvērtā pasaule'),
	(57, 'Kiberpanks'),
	(57, 'Atmosfēriska'),
	(57, 'Izpētīšana'),
	(57, 'Stratēģija'),
	(58, 'MMORPG'),
	(58, 'RPG'),
	(58, 'Fantāzija'),
	(58, 'JRPG'),
	(58, 'Bagāts stāsts'),
	(58, 'Atvērtā pasaule'),
	(58, 'Anime'),
	(58, 'Multiplayer'),
	(58, 'Piedzīvojumu'),
	(58, 'Asa sižeta'),
	(58, 'Atmosfēriska'),
	(58, 'Co-op'),
	(58, 'Viena spēlētāja'),
	(59, 'Sacīkšu'),
	(59, 'Sports'),
	(59, 'Atvērtā pasaule'),
	(59, 'Simulācija'),
	(59, 'Atmosfēriska'),
	(59, 'Piedzīvojumu'),
	(59, 'Multiplayer'),
	(59, 'Asa sižeta'),
	(59, 'Co-op'),
	(59, 'Viena spēlētāja'),
	(60, 'Simulācija'),
	(60, 'Būvēšana'),
	(60, 'Sandbox'),
	(60, 'Viena spēlētāja'),
	(60, 'Casual'),
	(60, 'RPG'),
	(60, 'Komēdija'),
	(60, 'Piedzīvojumu'),
	(60, 'Multiplayer'),
	(60, 'Kailums'),
	(60, 'Stratēģija'),
	(60, 'Asa sižeta'),
	(61, 'Indie'),
	(61, 'Puzzle'),
	(61, 'Platformas spēle'),
	(61, 'Atmosfēriska'),
	(61, 'Piedzīvojumu'),
	(61, '2D'),
	(61, 'Viena spēlētāja'),
	(61, 'Šausmu'),
	(61, 'Sirreāls'),
	(61, 'Asa sižeta'),
	(61, 'Casual'),
	(62, 'Loot'),
	(62, 'Šautene'),
	(62, 'Asa sižeta'),
	(62, 'Multiplayer'),
	(62, 'Co-op'),
	(62, 'FPS'),
	(62, 'RPG'),
	(62, 'Komēdija'),
	(62, 'Atvērtā pasaule'),
	(62, 'Piedzīvojumu'),
	(62, 'Viena spēlētāja'),
	(62, 'Zinātniskā fantastika'),
	(63, 'Šausmu'),
	(63, 'Atmosfēriska'),
	(63, 'Puzzle'),
	(63, 'Kailums'),
	(63, 'Piedzīvojumu'),
	(63, 'Indie'),
	(63, 'Viena spēlētāja'),
	(63, 'Asa sižeta'),
	(63, 'Izpētīšana'),
	(63, 'Maskēšanās'),
	(63, 'Sirreāls'),
	(63, 'Bagāts stāsts'),
	(64, 'Asa sižeta'),
	(64, 'Taktiskā'),
	(64, 'Zinātniskā fantastika'),
	(64, 'Viena spēlētāja'),
	(64, 'Stratēģija'),
	(64, 'Šautene'),
	(64, 'RPG'),
	(64, 'Piedzīvojumu'),
	(64, 'Atmosfēriska'),
	(64, 'Bagāts stāsts'),
	(64, 'Multiplayer'),
	(64, 'Atvērtā pasaule'),
	(64, 'Maskēšanās'),
	(64, 'Retro'),
	(64, 'Karš'),
	(65, 'Stratēģija'),
	(65, 'Zinātniskā fantastika'),
	(65, 'Kosmosā'),
	(65, 'Gājieniem balstīta'),
	(65, 'Multiplayer'),
	(65, 'Viena spēlētāja'),
	(65, 'Taktiskā'),
	(65, 'Izpētīšana'),
	(65, 'Atmosfēriska'),
	(65, 'Piedzīvojumu'),
	(65, 'Simulācija'),
	(65, 'Asa sižeta'),
	(66, 'Atvērtā pasaule'),
	(66, 'RPG'),
	(66, 'Fantāzija'),
	(66, 'Piedzīvojumu'),
	(66, 'Asa sižeta'),
	(66, 'Viduslaiku'),
	(66, 'Viena spēlētāja'),
	(66, 'Bagāts stāsts'),
	(66, 'Sandbox'),
	(66, 'Atmosfēriska'),
	(67, 'Puzzle'),
	(67, 'Retro'),
	(67, 'Atmosfēriska'),
	(67, '2D'),
	(67, 'Bagāts stāsts'),
	(67, 'Casual'),
	(67, 'Sirreāls'),
	(67, 'Piedzīvojumu'),
	(67, 'Viena spēlētāja'),
	(67, 'Indie'),
	(68, 'Stratēģija'),
	(68, 'RTS'),
	(68, 'Multiplayer'),
	(68, 'Vēsturisks'),
	(68, 'Karš'),
	(68, 'Simulācija'),
	(68, 'Reālā laika'),
	(68, 'Viena spēlētāja'),
	(68, 'Būvēšana'),
	(68, 'Atvērtā pasaule'),
	(68, 'Co-op'),
	(68, 'Asa sižeta'),
	(68, 'Piedzīvojumu'),
	(69, 'Sandbox'),
	(69, 'Izdzīvošana'),
	(69, '2D'),
	(69, 'Multiplayer'),
	(69, 'Piedzīvojumu'),
	(69, 'Amatniecība'),
	(69, 'Būvēšana'),
	(69, 'Izpētīšana'),
	(69, 'Co-op'),
	(69, 'Atvērtā pasaule'),
	(69, 'Indie'),
	(69, 'Asa sižeta'),
	(69, 'RPG'),
	(69, 'Viena spēlētāja'),
	(69, 'Platformas spēle'),
	(69, 'Atmosfēriska'),
	(70, 'Indie'),
	(70, 'Asa sižeta'),
	(70, 'Viena spēlētāja'),
	(70, 'RPG'),
	(70, 'Hack and Slash'),
	(70, 'Bagāts stāsts'),
	(70, 'Piedzīvojumu'),
	(70, 'Fantāzija'),
	(70, 'Atmosfēriska'),
	(70, 'Postapokaliptisks'),
	(70, '2D'),
	(70, 'Mūzika'),
	(71, 'Detektīvs'),
	(71, 'Atvērtā pasaule'),
	(71, 'Piedzīvojumu'),
	(71, 'Bagāts stāsts'),
	(71, 'Viena spēlētāja'),
	(71, 'Asa sižeta'),
	(71, 'Atmosfēriska'),
	(71, 'Kailums'),
	(71, 'Stratēģija'),
	(71, 'Puzzle'),
	(72, 'Indie'),
	(72, 'Asa sižeta'),
	(72, 'Viena spēlētāja'),
	(72, 'Piedzīvojumu'),
	(72, '2D'),
	(72, 'Izdzīvošana'),
	(72, 'RPG'),
	(73, 'Asa sižeta'),
	(73, 'Multiplayer'),
	(73, 'FPS'),
	(73, 'Šautene'),
	(73, 'Viena spēlētāja'),
	(73, 'Co-op'),
	(73, 'Karš'),
	(73, 'Izdzīvošana'),
	(73, 'Taktiskā'),
	(73, 'Piedzīvojumu'),
	(73, 'Zinātniskā fantastika'),
	(73, 'Šausmu'),
	(73, 'Atmosfēriska'),
	(74, 'Asa sižeta'),
	(74, 'FPS'),
	(74, 'Co-op'),
	(74, 'Komēdija'),
	(74, 'Multiplayer'),
	(74, 'Šautene'),
	(74, 'Viena spēlētāja'),
	(74, 'Piedzīvojumu'),
	(74, 'Indie'),
	(74, 'Zinātniskā fantastika'),
	(74, 'Atmosfēriska'),
	(74, 'Atvērtā pasaule'),
	(75, '2D'),
	(75, 'Hack and Slash'),
	(75, 'Co-op'),
	(75, 'Piedzīvojumu'),
	(75, 'Vietējā sadarbība'),
	(75, 'Multiplayer'),
	(75, 'Asa sižeta'),
	(75, 'Viena spēlētāja'),
	(75, 'Viduslaiku'),
	(75, 'Komēdija'),
	(75, 'RPG'),
	(75, 'Casual'),
	(76, 'Maskēšanās'),
	(76, 'Asa sižeta'),
	(76, 'Viena spēlētāja'),
	(76, 'Atmosfēriska'),
	(76, 'Bagāts stāsts'),
	(76, 'Piedzīvojumu'),
	(76, 'FPS'),
	(76, 'RPG'),
	(76, 'Fantāzija'),
	(76, 'Atvērtā pasaule'),
	(76, 'Šautene'),
	(77, 'Multiplayer'),
	(77, 'Sacīkšu'),
	(77, 'Indie'),
	(77, 'Sacensību'),
	(77, 'Platformas spēle'),
	(77, 'Asa sižeta'),
	(77, '2D'),
	(77, 'Sports'),
	(77, 'Vietējā sadarbība'),
	(77, 'Co-op'),
	(77, 'Viena spēlētāja'),
	(77, 'Supervaroņi'),
	(78, 'Asa sižeta'),
	(78, 'Atvērtā pasaule'),
	(78, 'Supervaroņi'),
	(78, 'Maskēšanās'),
	(78, 'Piedzīvojumu'),
	(78, 'Viena spēlētāja'),
	(78, 'Detektīvs'),
	(78, 'Cīņa'),
	(78, 'Bagāts stāsts'),
	(78, 'Atmosfēriska'),
	(78, 'Puzzle'),
	(78, 'Sandbox'),
	(78, 'Stratēģija'),
	(78, 'Šausmu'),
	(79, 'Kosmosā'),
	(79, 'Stratēģija'),
	(79, 'Zinātniskā fantastika'),
	(79, 'Indie'),
	(79, 'Viena spēlētāja'),
	(79, '2D'),
	(79, 'Simulācija'),
	(79, 'Izdzīvošana'),
	(79, 'Piedzīvojumu'),
	(79, 'RPG'),
	(79, 'Atmosfēriska'),
	(80, 'Šausmu'),
	(80, 'Zinātniskā fantastika'),
	(80, 'Atmosfēriska'),
	(80, 'Maskēšanās'),
	(80, 'Kosmosā'),
	(80, 'Izdzīvošana'),
	(80, 'Viena spēlētāja'),
	(80, 'Asa sižeta'),
	(80, 'Piedzīvojumu'),
	(80, 'FPS'),
	(80, 'Šautene'),
	(80, 'VR'),
	(81, 'Asa sižeta'),
	(81, 'Indie'),
	(81, 'Retro'),
	(81, 'Viena spēlētāja'),
	(81, 'Sirreāls'),
	(81, 'Šautene'),
	(81, '2D'),
	(81, 'Atmosfēriska'),
	(81, 'Mūzika'),
	(82, 'Kosmosā'),
	(82, 'Simulācija'),
	(82, 'Sandbox'),
	(82, 'Būvēšana'),
	(82, 'Indie'),
	(82, 'Atvērtā pasaule'),
	(82, 'Viena spēlētāja'),
	(82, 'Izpētīšana'),
	(82, 'Zinātniskā fantastika'),
	(82, 'Piedzīvojumu'),
	(82, 'Stratēģija'),
	(82, 'Komēdija'),
	(83, 'Atvērtā pasaule'),
	(83, 'FPS'),
	(83, 'Asa sižeta'),
	(83, 'Piedzīvojumu'),
	(83, 'Multiplayer'),
	(83, 'Šautene'),
	(83, 'Maskēšanās'),
	(83, 'Co-op'),
	(83, 'Viena spēlētāja'),
	(83, 'Sandbox'),
	(83, 'Izdzīvošana'),
	(83, 'Bagāts stāsts'),
	(83, 'Atmosfēriska'),
	(83, 'Kailums'),
	(83, 'Amatniecība'),
	(83, 'RPG'),
	(84, 'Asa sižeta'),
	(84, 'Hack and Slash'),
	(84, 'Piedzīvojumu'),
	(84, 'Viena spēlētāja'),
	(84, 'Atmosfēriska'),
	(84, 'Komēdija'),
	(84, 'Bagāts stāsts'),
	(84, 'Fantāzija'),
	(84, 'Platformas spēle'),
	(85, 'Asa sižeta'),
	(85, 'Zombiji'),
	(85, 'Co-op'),
	(85, 'Šausmu'),
	(85, 'Piedzīvojumu'),
	(85, 'Multiplayer'),
	(85, 'Šautene'),
	(85, 'Vietējā sadarbība'),
	(85, 'Izdzīvošana'),
	(85, 'Viena spēlētāja'),
	(85, 'Atmosfēriska'),
	(85, 'Casual'),
	(86, 'Izdzīvošana'),
	(86, 'Amatniecība'),
	(86, 'Piedzīvojumu'),
	(86, 'Indie'),
	(86, 'Sandbox'),
	(86, 'Viena spēlētāja'),
	(86, 'Atvērtā pasaule'),
	(86, 'Izpētīšana'),
	(86, 'Multiplayer'),
	(86, 'Simulācija'),
	(86, '2D'),
	(86, 'Šausmu'),
	(87, 'Komēdija'),
	(87, 'Indie'),
	(87, 'Psiholoģiskā'),
	(87, 'Piedzīvojumu'),
	(87, 'Izpētīšana'),
	(87, 'Viena spēlētāja'),
	(87, 'Izvēlei ir nozīme'),
	(87, 'Bagāts stāsts'),
	(87, 'Sirreāls'),
	(87, 'Atmosfēriska'),
	(87, 'Puzzle'),
	(87, 'Casual'),
	(88, 'RPG'),
	(88, 'Gājieniem balstīta'),
	(88, 'Co-op'),
	(88, 'Fantāzija'),
	(88, 'Piedzīvojumu'),
	(88, 'Stratēģija'),
	(88, 'Atvērtā pasaule'),
	(88, 'Bagāts stāsts'),
	(88, 'Indie'),
	(88, 'Multiplayer'),
	(88, 'Viena spēlētāja'),
	(88, 'Atmosfēriska'),
	(89, 'Sandbox'),
	(89, 'Kosmosā'),
	(89, 'Simulācija'),
	(89, 'Reālistisks'),
	(89, 'Viena spēlētāja'),
	(89, 'VR'),
	(89, 'Atvērtā pasaule'),
	(89, 'Indie'),
	(89, 'Casual'),
	(89, 'Atmosfēriska'),
	(89, 'Zinātniskā fantastika'),
	(89, 'Izpētīšana'),
	(90, 'Asa sižeta'),
	(90, 'RPG'),
	(90, 'Co-op'),
	(90, 'Viena spēlētāja'),
	(90, 'PvE'),
	(90, 'Zinātniskā fantastika'),
	(90, 'Kosmosā'),
	(90, 'Šautene'),
	(90, 'Hack and Slash'),
	(91, 'Simulācija'),
	(91, 'Komēdija'),
	(91, 'Indie'),
	(91, 'Puzzle'),
	(91, 'VR'),
	(91, 'Casual'),
	(91, 'Viena spēlētāja'),
	(91, 'Asa sižeta'),
	(92, 'Atvērtā pasaule'),
	(92, 'Sandbox'),
	(92, 'RPG'),
	(92, 'Izdzīvošana'),
	(92, 'Stratēģija'),
	(92, 'Būvēšana'),
	(92, 'Postapokaliptisks'),
	(92, 'Viena spēlētāja'),
	(92, 'Amatniecība'),
	(92, 'Indie'),
	(92, 'Simulācija'),
	(92, 'Piedzīvojumu'),
	(92, 'Vadība'),
	(92, 'RTS'),
	(93, 'Indie'),
	(93, 'Kiberpanks'),
	(93, 'Bagāts stāsts'),
	(93, 'Zinātniskā fantastika'),
	(93, 'Viena spēlētāja'),
	(93, 'RPG'),
	(93, 'Skaists'),
	(93, 'Atmosfēriska'),
	(93, 'Asa sižeta'),
	(93, 'Stratēģija'),
	(93, 'Taktiskā'),
	(93, 'Piedzīvojumu'),
	(93, 'Gājieniem balstīta'),
	(93, 'Hack and Slash'),
	(94, 'Piedzīvojumu'),
	(94, 'Detektīvs'),
	(94, 'Bagāts stāsts'),
	(94, 'Izvēlei ir nozīme'),
	(94, 'Viena spēlētāja'),
	(94, 'Atmosfēriska'),
	(94, 'Asa sižeta'),
	(94, 'Fantāzija'),
	(94, 'Casual'),
	(95, 'Izdzīvošana'),
	(95, 'Zombiji'),
	(95, 'Amatniecība'),
	(95, 'Asa sižeta'),
	(95, 'Co-op'),
	(95, 'Multiplayer'),
	(95, 'RPG'),
	(95, 'Vietējā sadarbība'),
	(95, 'Piedzīvojumu'),
	(95, 'Atvērtā pasaule'),
	(95, 'Hack and Slash'),
	(95, 'Postapokaliptisks'),
	(95, 'Viena spēlētāja'),
	(95, 'Komēdija'),
	(95, 'Indie'),
	(96, 'Indie'),
	(96, 'Viena spēlētāja'),
	(96, '2D'),
	(96, 'Vietējā sadarbība'),
	(96, 'Atmosfēriska'),
	(96, 'Asa sižeta'),
	(96, 'Co-op'),
	(96, 'Šausmu'),
	(97, 'Izdzīvošana'),
	(97, 'Amatniecība'),
	(97, 'Multiplayer'),
	(97, 'Atvērtā pasaule'),
	(97, 'Būvēšana'),
	(97, 'Sandbox'),
	(97, 'Piedzīvojumu'),
	(97, 'Asa sižeta'),
	(97, 'FPS'),
	(97, 'Kailums'),
	(97, 'Co-op'),
	(97, 'Šautene'),
	(97, 'Indie'),
	(97, 'Postapokaliptisks'),
	(97, 'Simulācija'),
	(98, 'Multiplayer'),
	(98, 'Sacensību'),
	(98, 'Sports'),
	(98, 'Sacīkšu'),
	(98, 'Co-op'),
	(98, 'Asa sižeta'),
	(98, 'Vietējā sadarbība'),
	(98, 'Viena spēlētāja'),
	(98, 'Casual'),
	(98, 'Indie'),
	(99, 'Asa sižeta'),
	(99, 'Zombiji'),
	(99, 'Šausmu'),
	(99, 'Viena spēlētāja'),
	(99, 'Piedzīvojumu'),
	(99, 'Atmosfēriska'),
	(99, 'Izdzīvošana'),
	(99, 'Šautene'),
	(99, 'Multiplayer'),
	(100, 'Simulācija'),
	(100, 'Būvēšana'),
	(100, 'Vadība'),
	(100, 'Stratēģija'),
	(100, 'Sandbox'),
	(100, 'Viena spēlētāja'),
	(100, 'Reālistisks'),
	(100, 'Casual'),
	(100, 'Asa sižeta'),
	(101, 'Atvērtā pasaule'),
	(101, 'Simulācija'),
	(101, 'Reālistisks'),
	(101, 'Izpētīšana'),
	(101, 'Atmosfēriska'),
	(101, 'Vadība'),
	(101, 'Multiplayer'),
	(101, 'Viena spēlētāja'),
	(101, 'Piedzīvojumu'),
	(101, 'Casual'),
	(102, 'Atvērtā pasaule'),
	(102, 'Asa sižeta'),
	(102, 'Multiplayer'),
	(102, 'Šautene'),
	(102, 'Piedzīvojumu'),
	(102, 'Viena spēlētāja'),
	(102, 'Sacīkšu'),
	(102, 'Co-op'),
	(102, 'Atmosfēriska'),
	(102, 'Sandbox'),
	(102, 'Komēdija'),
	(103, 'Zombiji'),
	(103, 'Šausmu'),
	(103, 'Atmosfēriska'),
	(103, 'Viena spēlētāja'),
	(103, 'Puzzle'),
	(103, 'Izdzīvošana'),
	(103, 'Piedzīvojumu'),
	(103, 'Asa sižeta'),
	(103, 'Bagāts stāsts'),
	(103, 'Šautene'),
	(104, 'Viduslaiku'),
	(104, 'Asa sižeta'),
	(104, 'Multiplayer'),
	(104, 'Cīņa'),
	(104, 'Karš'),
	(104, 'Co-op'),
	(104, 'Viena spēlētāja'),
	(104, 'Hack and Slash'),
	(104, 'Reālistisks'),
	(104, 'Stratēģija'),
	(104, 'Atmosfēriska'),
	(104, 'RPG'),
	(104, 'Fantāzija'),
	(104, 'MOBA'),
	(104, 'Bagāts stāsts'),
	(105, 'Cīņa'),
	(105, 'Asa sižeta'),
	(105, 'Multiplayer'),
	(105, 'Sacensību'),
	(105, 'Atmosfēriska'),
	(105, 'Viena spēlētāja'),
	(105, 'Fantāzija'),
	(105, 'Šausmu'),
	(106, 'Cīņa'),
	(106, 'Asa sižeta'),
	(106, 'Multiplayer'),
	(106, 'Sacensību'),
	(106, 'Anime'),
	(106, 'Viena spēlētāja'),
	(106, '2D'),
	(106, 'Kailums'),
	(107, 'Šausmu'),
	(107, 'Viena spēlētāja'),
	(107, 'Indie'),
	(107, 'Izdzīvošana'),
	(107, 'Atmosfēriska'),
	(107, 'Vēsturisks'),
	(108, 'FPS'),
	(108, 'Asa sižeta'),
	(108, 'Šautene'),
	(108, 'Viena spēlētāja'),
	(108, 'Multiplayer'),
	(108, 'Zinātniskā fantastika'),
	(108, 'Šausmu'),
	(108, 'Atmosfēriska'),
	(108, 'Zombiji'),
	(108, 'Co-op'),
	(109, 'VR'),
	(109, 'Anime'),
	(109, 'Multiplayer'),
	(109, 'Atvērtā pasaule'),
	(109, 'Simulācija'),
	(109, 'Casual'),
	(109, 'Piedzīvojumu'),
	(109, 'MMORPG'),
	(109, 'Komēdija'),
	(109, 'Sandbox'),
	(109, 'Asa sižeta'),
	(109, 'Atmosfēriska'),
	(110, 'Bagāts stāsts'),
	(110, 'Asa sižeta'),
	(110, 'Hack and Slash'),
	(110, 'RPG'),
	(110, 'Atvērtā pasaule'),
	(110, 'JRPG'),
	(110, 'Anime'),
	(110, 'Postapokaliptisks'),
	(110, 'Viena spēlētāja'),
	(110, 'Atmosfēriska'),
	(110, 'Zinātniskā fantastika'),
	(110, 'Kailums'),
	(110, 'Piedzīvojumu'),
	(111, 'Atvērtā pasaule'),
	(111, 'Multiplayer'),
	(111, 'Amatniecība'),
	(111, 'Co-op'),
	(111, 'Būvēšana'),
	(111, 'Sandbox'),
	(111, 'Izpētīšana'),
	(111, 'Piedzīvojumu'),
	(111, 'Simulācija'),
	(111, 'Izdzīvošana'),
	(111, 'Stratēģija'),
	(111, 'Zinātniskā fantastika'),
	(111, 'Viena spēlētāja'),
	(111, 'Indie'),
	(112, 'VR'),
	(112, 'FPS'),
	(112, 'Bagāts stāsts'),
	(112, 'Šausmu'),
	(112, 'Šautene'),
	(112, 'Viena spēlētāja'),
	(112, 'Asa sižeta'),
	(112, 'Zombiji'),
	(112, 'Zinātniskā fantastika'),
	(112, 'Atmosfēriska'),
	(112, 'Skaists'),
	(112, 'Piedzīvojumu'),
	(113, 'Bagāts stāsts'),
	(113, 'Izvēlei ir nozīme'),
	(113, 'Atmosfēriska'),
	(113, 'Viena spēlētāja'),
	(113, 'Piedzīvojumu'),
	(113, 'Drāma'),
	(113, 'Asa sižeta'),
	(113, 'Indie'),
	(114, 'Simulācija'),
	(114, 'Būvēšana'),
	(114, 'Vadība'),
	(114, 'Sandbox'),
	(114, '3D'),
	(114, 'Casual'),
	(114, 'Reālistisks'),
	(114, 'Viena spēlētāja'),
	(114, 'Puzzle'),
	(114, 'Atmosfēriska'),
	(114, 'Indie'),
	(115, 'RPG'),
	(115, 'Bagāts stāsts'),
	(115, 'Izvēlei ir nozīme'),
	(115, 'Detektīvs'),
	(115, 'Atmosfēriska'),
	(115, 'Viena spēlētāja'),
	(115, 'Sirreāls'),
	(115, 'Piedzīvojumu'),
	(115, 'Indie'),
	(115, 'Izpētīšana'),
	(115, 'Atvērtā pasaule'),
	(116, 'VR'),
	(116, 'Asa sižeta'),
	(116, 'Sandbox'),
	(116, 'Šautene'),
	(116, 'Viena spēlētāja'),
	(116, 'Piedzīvojumu'),
	(116, 'Puzzle'),
	(116, 'Simulācija'),
	(116, 'Reālistisks'),
	(116, 'FPS'),
	(116, 'Indie'),
	(116, 'Šausmu'),
	(116, 'Zinātniskā fantastika'),
	(117, 'Cīņa'),
	(117, 'Multiplayer'),
	(117, 'Asa sižeta'),
	(117, 'Sacensību'),
	(117, 'Viena spēlētāja'),
	(117, 'Bagāts stāsts'),
	(117, 'Atmosfēriska'),
	(117, 'Šausmu'),
	(118, 'Atvērtā pasaule'),
	(118, 'FPS'),
	(118, 'MMORPG'),
	(118, 'Co-op'),
	(118, 'PvE'),
	(118, 'Šautene'),
	(118, 'Multiplayer'),
	(118, 'Zinātniskā fantastika'),
	(118, 'Loot'),
	(118, 'Asa sižeta'),
	(118, 'Piedzīvojumu'),
	(118, 'Kosmosā'),
	(118, 'Sacensību'),
	(118, 'Atmosfēriska'),
	(119, 'RPG'),
	(119, 'Izvēlei ir nozīme'),
	(119, 'Bagāts stāsts'),
	(119, 'Fantāzija'),
	(119, 'PvE'),
	(119, 'Maskēšanās'),
	(119, 'Amatniecība');
