INSERT INTO Žanrs (Nosaukums) VALUES 
('Hack and Slash'),
('Loot'),
('Otrais pasaules karš'),
('Supervaroņi'),
('Būvēšana'),
('Kiberpanks'),
('Daudzspēlētāju PvP'),
('Vadība'),
('3D'),
('Vecā skola'),
('Retro'),
('Zinātniskā fantastika'),
('Anime'),
('2D'),
('Kailums'),
('Vietējā sadarbība'),
('Sacensību'),
('Amatniecība'),
('Sirreāls'),
('JRPG'),
('Psiholoģiskā'),
('Cīņa'),
('Puzzle'),
('Skaists'),
('Kosmosā'),
('PvE'),
('Izpētīšana'),
('Drāma'),
('Multiplayer'),
('Reālistisks'),
('Reālā laika'),
('Viena spēlētāja'),
('Atmosfēriska'),
('Viduslaiku'),
('Detektīvs'),
('Atvērtā pasaule'),
('Komēdija'),
('Taktiskā'),
('Karš'),
('Vēsturisks'),
('Fantāzija'),
('Bagāts stāsts'),
('Postapokaliptisks'),
('Zombiji'),
('Izvēlei ir nozīme');
